In [ ]:
# Cell 1: Load and prepare GSE data
import pandas as pd
import numpy as np
import os
import pickle
from datetime import datetime
from biolearn.data_library import DataLibrary

def _log(message: str) -> None:
    """Log a message with timestamp."""
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] {message}")

def load_gse_data(accession: str):
    """
    Load GSE data using biolearn and save locally as CSV files.
    
    Args:
        accession (str): GSE accession number (e.g., 'GSE42861')
    
    Returns:
        tuple: (dnam_df, metadata_df) - methylation data and metadata as pandas DataFrames
    """
    _log(f"Starting {accession} data loading...")
    
    # Create local data directory
    data_dir = "2_poc_simulacra"
    os.makedirs(data_dir, exist_ok=True)
    
    # Check if data already exists
    dnam_path = os.path.join(data_dir, f"{accession}_dnam.csv")
    metadata_path = os.path.join(data_dir, f"{accession}_metadata.csv")
    
    if os.path.exists(dnam_path) and os.path.exists(metadata_path):
        _log(f"Loading existing {accession} data from local files...")
        dnam_df = pd.read_csv(dnam_path, index_col=0)
        metadata_df = pd.read_csv(metadata_path, index_col=0)
        _log(f"Loaded {accession}_dnam.csv: {dnam_df.shape[0]} rows, {dnam_df.shape[1]} columns")
        _log(f"Loaded {accession}_metadata.csv: {metadata_df.shape[0]} rows, {metadata_df.shape[1]} columns")
        return dnam_df, metadata_df
    
    _log(f"Downloading {accession} data from biolearn (LONG OPERATION)...")
    start_time = datetime.now()
    
    # Load data using biolearn
    library = DataLibrary()
    data = library.get(accession)
    if data is None:
        raise ValueError(f"{accession} dataset not found in biolearn library")
    
    data = data.load()
    
    # Extract methylation data (transpose to have samples as rows)
    dnam_df = data.dnam.T
    metadata_df = data.metadata.copy()
    
    # Ensure index alignment
    common_samples = dnam_df.index.intersection(metadata_df.index)
    dnam_df = dnam_df.loc[common_samples]
    metadata_df = metadata_df.loc[common_samples]
    
    download_duration = datetime.now() - start_time
    _log(f"Data download completed in {download_duration.total_seconds():.2f} seconds")
    
    _log(f"Saving {accession} data to local CSV files (LONG OPERATION)...")
    save_start = datetime.now()
    
    # Save methylation data
    dnam_df.to_csv(dnam_path)
    _log(f"Saved {accession}_dnam.csv: {dnam_df.shape[0]} rows, {dnam_df.shape[1]} columns")
    
    # Save metadata
    metadata_df.to_csv(metadata_path)
    _log(f"Saved {accession}_metadata.csv: {metadata_df.shape[0]} rows, {metadata_df.shape[1]} columns")
    
    save_duration = datetime.now() - save_start
    _log(f"Data saving completed in {save_duration.total_seconds():.2f} seconds")
    
    return dnam_df, metadata_df

# Execute the function for GSE42861
dnam_df, metadata_df = load_gse_data('GSE42861')

_log("GSE42861 data loading completed successfully!")
_log(f"Final dnam shape: {dnam_df.shape}")
_log(f"Final metadata shape: {metadata_df.shape}")
_log(f"Metadata columns: {list(metadata_df.columns)}")

[2025-10-12 12:30:34] Starting GSE42861 data loading...
[2025-10-12 12:30:34] Downloading GSE42861 data from biolearn (LONG OPERATION)...
[2025-10-12 12:30:49] Data download completed in 14.56 seconds
[2025-10-12 12:30:49] Saving data to local CSV files (LONG OPERATION)...
[2025-10-12 12:48:22] Saved dnam.csv: 689 rows, 485577 columns
[2025-10-12 12:48:22] Saved metadata.csv: 689 rows, 4 columns
[2025-10-12 12:48:22] Data saving completed in 1052.84 seconds
[2025-10-12 12:48:22] GSE42861 data loading completed successfully!
[2025-10-12 12:48:22] Final dnam shape: (689, 485577)
[2025-10-12 12:48:22] Final metadata shape: (689, 4)
[2025-10-12 12:48:22] Metadata columns: ['disease', 'age', 'sex', 'smoking']

In [ ]:
# Cell 2: Generate embeddings with Pythae
import os
import sys
import torch
import pandas as pd
import numpy as np
from datetime import datetime
from tqdm import tqdm
from pythae.models import VAE, VAEConfig
from pythae.trainers import BaseTrainerConfig
from pythae.pipelines.training import TrainingPipeline
import glob

# Import our custom dataset classes
from iterable_csv_dataset import PythaeIterableDataset, DNAmDataset

def _log(message: str) -> None:
    """Log a message with timestamp."""
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] {message}")

def find_model_path(model_dir):
    """Find the actual model path within the timestamped subdirectory."""
    if not os.path.exists(model_dir):
        return None
    
    # Look for VAE_training_* directories
    training_dirs = glob.glob(os.path.join(model_dir, "VAE_training_*"))
    if not training_dirs:
        return None
    
    # Get the most recent training directory
    latest_training_dir = max(training_dirs, key=os.path.getctime)
    final_model_path = os.path.join(latest_training_dir, "final_model")
    
    if os.path.exists(final_model_path):
        return final_model_path
    return None

def generate_embeddings_with_pythae(accession: str, n_dnam_cols: int = 100, latent_dim: int = 512, epochs: int = 20):
    """
    Generate embeddings using Pythae VAE on GSE data.
    
    Args:
        accession (str): GSE accession number (e.g., 'GSE42861')
        n_dnam_cols (int): Number of DNAm columns to use for training
        latent_dim (int): Latent dimension for VAE
        epochs (int): Number of training epochs
    
    Returns:
        str: Path to the generated embeddings CSV file
    """
    _log(f"Starting Pythae embedding generation for {accession}...")
    
    # Create local data directory
    data_dir = "2_poc_simulacra"
    os.makedirs(data_dir, exist_ok=True)
    
    # Define paths - use the actual file names that exist
    embeddings_path = os.path.join(data_dir, f"{accession}_embeddings.csv")
    model_dir = os.path.join(data_dir, f"{accession}_vae_model")
    dnam_path = os.path.join(data_dir, "dnam.csv")
    metadata_path = os.path.join(data_dir, "metadata.csv")
    
    # Check if embeddings already exist
    if os.path.exists(embeddings_path):
        _log(f"Loading existing embeddings from {embeddings_path}...")
        embeddings_df = pd.read_csv(embeddings_path, index_col=0)
        _log(f"Loaded embeddings: {embeddings_df.shape[0]} rows, {embeddings_df.shape[1]} columns")
        return embeddings_path
    
    # Check if model already exists
    model_path = find_model_path(model_dir)
    if model_path:
        _log(f"Loading existing VAE model from {model_path}...")
        model = VAE.load_from_folder(model_path)
        _log("VAE model loaded successfully")
    else:
        _log("Training new VAE model (LONG OPERATION)...")
        train_start = datetime.now()
        
        # Create train/validation split
        ds = {}
        ds['train'], ds['val'] = DNAmDataset.split_dataset(
            split_points=0.8,
            dnam_path=dnam_path,
            metadata_path=metadata_path,
            n_dnam_cols=n_dnam_cols,
            target_metadata_col="disease",
            target_metadata_type="categorical",
            shuffle=True,
            seed=42,
            on_unmatched='warn',
            join_on='Unnamed: 0',
        )
        
        _log(f"Dataset split created - Train: {len(ds['train'])}, Val: {len(ds['val'])}")
        
        # Create VAE model
        model_config = VAEConfig(
            input_dim=(n_dnam_cols,),
            latent_dim=latent_dim
        )
        
        # Create training config
        training_config = BaseTrainerConfig(
            output_dir=model_dir,
            learning_rate=1e-3,
            per_device_train_batch_size=512,
            per_device_eval_batch_size=512,
            num_epochs=epochs,
            keep_best_on_train=True
        )
        
        # Create training pipeline
        pipeline = TrainingPipeline(
            model=VAE(model_config=model_config),
            training_config=training_config
        )
        
        # Train the model
        pipeline(
            train_data=ds['train'],
            eval_data=ds['val']
        )
        
        train_duration = datetime.now() - train_start
        _log(f"VAE training completed in {train_duration.total_seconds():.2f} seconds")
        
        # Find and load the trained model
        model_path = find_model_path(model_dir)
        if model_path:
            model = VAE.load_from_folder(model_path)
            _log("VAE model loaded successfully")
        else:
            raise FileNotFoundError(f"Could not find trained model in {model_dir}")
    
    # Generate embeddings for all data
    _log("Generating embeddings for all data (LONG OPERATION)...")
    embed_start = datetime.now()
    
    # Create dataset for all data
    all_ds = PythaeIterableDataset(
        dnam_path=dnam_path,
        metadata_path=metadata_path,
        n_dnam_cols=n_dnam_cols,
        target_metadata_col="disease",
        target_metadata_type="categorical",
        join_on="Unnamed: 0",
    )
    
    # Get the list of indices from metadata
    index_list = list(all_ds.metadata.index)
    
    # Generate embeddings
    model.eval()
    buffer = []
    with torch.no_grad():
        with open(embeddings_path, 'w') as fout:
            header = ','.join([f'emb_{i}' for i in range(model.latent_dim)])
            fout.write(f'id,{header}\n')
            
            for idx, (X, _) in tqdm(enumerate(all_ds), desc="Generating embeddings"):
                X_tensor = X.to(dtype=torch.float32).unsqueeze(0)
                embedding = model.encoder(X_tensor)['embedding'].cpu().numpy().squeeze()
                
                # Use the original index from metadata
                row_id = index_list[idx] if idx < len(index_list) else idx
                row = ','.join([str(x) for x in embedding])
                buffer.append(f'{row_id},{row}\n')
                
                # Write buffer periodically
                if len(buffer) >= 64:
                    fout.writelines(buffer)
                    buffer.clear()
            
            # Write remaining buffer
            if buffer:
                fout.writelines(buffer)
    
    embed_duration = datetime.now() - embed_start
    _log(f"Embedding generation completed in {embed_duration.total_seconds():.2f} seconds")
    
    # Load and display the embeddings
    embeddings_df = pd.read_csv(embeddings_path, index_col=0)
    _log(f"Generated embeddings: {embeddings_df.shape[0]} rows, {embeddings_df.shape[1]} columns")
    
    return embeddings_path

# Execute the function for GSE42861
embeddings_path = generate_embeddings_with_pythae('GSE42861', n_dnam_cols=100, latent_dim=512, epochs=20)

_log("Pythae embedding generation completed successfully!")
_log(f"Embeddings saved to: {embeddings_path}")

# Display first few rows of embeddings
embeddings_df = pd.read_csv(embeddings_path, index_col=0)
_log(f"Final embeddings shape: {embeddings_df.shape}")
_log("First 5 rows of embeddings:")
display(embeddings_df)

[2025-10-12 21:47:43] Starting Pythae embedding generation for GSE42861...
[2025-10-12 21:47:43] Loading existing VAE model from 2_poc_simulacra\GSE42861_vae_model\VAE_training_2025-10-12_20-48-52\final_model...
[2025-10-12 21:47:44] VAE model loaded successfully
[2025-10-12 21:47:44] Generating embeddings for all data (LONG OPERATION)...

Generating embeddings: 689it [02:00,  5.74it/s]

[2025-10-12 21:49:44] Embedding generation completed in 120.31 seconds
[2025-10-12 21:49:44] Generated embeddings: 689 rows, 512 columns
[2025-10-12 21:49:44] Pythae embedding generation completed successfully!
[2025-10-12 21:49:44] Embeddings saved to: 2_poc_simulacra\GSE42861_embeddings.csv
[2025-10-12 21:49:44] Final embeddings shape: (689, 512)
[2025-10-12 21:49:44] First 5 rows of embeddings:
               emb_0     emb_1     emb_2     emb_3     emb_4     emb_5  \
id
GSM1051525  0.000379  0.007248 -0.011952 -0.006601 -0.002977  0.001650
GSM1051526 -0.002986  0.003322 -0.002674 -0.010356  0.005399  0.009582
GSM1051527 -0.006568  0.003980  0.000052 -0.007087 -0.002809  0.004245
GSM1051528  0.000215  0.009518 -0.009776 -0.007672  0.004302  0.010845
GSM1051529 -0.001178  0.006284 -0.006167 -0.007700  0.001529  0.008875

               emb_6     emb_7     emb_8     emb_9  ...   emb_502   emb_503  \
id                                                  ...
GSM1051525 -0.002853 -0.006493 -0.003603  0.002815  ...  0.001855  0.004305
GSM1051526 -0.007116 -0.010195  0.004752  0.000441  ...  0.002104  0.006323
GSM1051527 -0.003250 -0.004742  0.003934  0.003749  ...  0.005058  0.002357
GSM1051528 -0.001150 -0.007701  0.006775 -0.005619  ...  0.004212  0.011965
GSM1051529 -0.003372 -0.004588  0.002095  0.000175  ...  0.004174  0.004763

             emb_504   emb_505   emb_506   emb_507   emb_508   emb_509  \
id
GSM1051525  0.002511  0.002612  0.007929 -0.006192 -0.000926 -0.000606
GSM1051526  0.003349  0.000850  0.008739 -0.000499 -0.003584 -0.003576
GSM1051527  0.002605  0.004585  0.003063 -0.010164 -0.005583 -0.003053
GSM1051528  0.009021 -0.004224  0.006240  0.002095  0.002774 -0.006467
GSM1051529  0.007382  0.001549  0.006101 -0.000170  0.001114 -0.002347

             emb_510   emb_511
id
GSM1051525  0.011051  0.003112
GSM1051526  0.008540 -0.003069
GSM1051527  0.012815  0.001405
GSM1051528 -0.000980 -0.003478
GSM1051529  0.005288 -0.000686

[5 rows x 512 columns]

In [9]:
# Cell 3: Combine embeddings with target column
import pandas as pd
import numpy as np
from datetime import datetime

def _log(message: str) -> None:
    """Log a message with timestamp."""
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] {message}")

def create_embeddings_with_target(accession: str, target_col: str = "disease"):
    """
    Create a new dataframe combining embeddings with target column.
    
    Args:
        accession (str): GSE accession number (e.g., 'GSE42861')
        target_col (str): Name of the target column from metadata
    
    Returns:
        pd.DataFrame: Combined dataframe with target as first column, followed by embeddings
    """
    _log(f"Creating combined dataframe for {accession} with target column '{target_col}'...")
    
    # Define paths
    data_dir = "2_poc_simulacra"
    embeddings_path = os.path.join(data_dir, f"{accession}_embeddings.csv")
    metadata_path = os.path.join(data_dir, "metadata.csv")
    combined_path = os.path.join(data_dir, f"{accession}_embeddings_with_target.csv")
    
    # Check if combined file already exists
    if os.path.exists(combined_path):
        _log(f"Loading existing combined dataframe from {combined_path}...")
        combined_df = pd.read_csv(combined_path, index_col=0)
        _log(f"Loaded combined dataframe: {combined_df.shape[0]} rows, {combined_df.shape[1]} columns")
        return combined_df
    
    # Load embeddings and metadata
    _log("Loading embeddings and metadata...")
    embeddings_df = pd.read_csv(embeddings_path, index_col=0)
    metadata_df = pd.read_csv(metadata_path, index_col=0)
    
    _log(f"Embeddings shape: {embeddings_df.shape}")
    _log(f"Metadata shape: {metadata_df.shape}")
    
    # Check if target column exists in metadata
    if target_col not in metadata_df.columns:
        available_cols = list(metadata_df.columns)
        raise ValueError(f"Target column '{target_col}' not found in metadata. Available columns: {available_cols}")
    
    # Join on index to combine the dataframes
    _log("Combining embeddings with target column...")
    combined_df = pd.concat([metadata_df[[target_col]], embeddings_df], axis=1, join='inner')
    
    _log(f"Combined dataframe shape: {combined_df.shape}")
    _log(f"Target column '{target_col}' unique values: {combined_df[target_col].unique()}")
    
    # Save the combined dataframe
    _log(f"Saving combined dataframe to {combined_path}...")
    combined_df.to_csv(combined_path)
    _log("Combined dataframe saved successfully")
    
    return combined_df

# Execute the function for GSE42861
combined_df = create_embeddings_with_target('GSE42861', target_col='disease')

_log("Combined dataframe creation completed successfully!")
_log(f"Final combined dataframe shape: {combined_df.shape}")
_log(f"Columns: {list(combined_df.columns)}")
_log("First 5 rows:")
display(combined_df)

[2025-10-12 22:03:27] Creating combined dataframe for GSE42861 with target column 'disease'...
[2025-10-12 22:03:27] Loading embeddings and metadata...
[2025-10-12 22:03:27] Embeddings shape: (689, 512)
[2025-10-12 22:03:27] Metadata shape: (689, 4)
[2025-10-12 22:03:27] Combining embeddings with target column...
[2025-10-12 22:03:27] Combined dataframe shape: (689, 513)
[2025-10-12 22:03:27] Target column 'disease' unique values: ['rheumatoid arthritis' 'Normal']
[2025-10-12 22:03:27] Saving combined dataframe to 2_poc_simulacra\GSE42861_embeddings_with_target.csv...
[2025-10-12 22:03:28] Combined dataframe saved successfully
[2025-10-12 22:03:28] Combined dataframe creation completed successfully!
[2025-10-12 22:03:28] Final combined dataframe shape: (689, 513)
[2025-10-12 22:03:28] Columns: ['disease', 'emb_0', 'emb_1', 'emb_2', 'emb_3', 'emb_4', 'emb_5', 'emb_6', 'emb_7', 'emb_8', 'emb_9', 'emb_10', 'emb_11', 'emb_12', 'emb_13', 'emb_14', 'emb_15', 'emb_16', 'emb_17', 'emb_18', 'emb_19', 'emb_20', 'emb_21', 'emb_22', 'emb_23', 'emb_24', 'emb_25', 'emb_26', 'emb_27', 'emb_28', 'emb_29', 'emb_30', 'emb_31', 'emb_32', 'emb_33', 'emb_34', 'emb_35', 'emb_36', 'emb_37', 'emb_38', 'emb_39', 'emb_40', 'emb_41', 'emb_42', 'emb_43', 'emb_44', 'emb_45', 'emb_46', 'emb_47', 'emb_48', 'emb_49', 'emb_50', 'emb_51', 'emb_52', 'emb_53', 'emb_54', 'emb_55', 'emb_56', 'emb_57', 'emb_58', 'emb_59', 'emb_60', 'emb_61', 'emb_62', 'emb_63', 'emb_64', 'emb_65', 'emb_66', 'emb_67', 'emb_68', 'emb_69', 'emb_70', 'emb_71', 'emb_72', 'emb_73', 'emb_74', 'emb_75', 'emb_76', 'emb_77', 'emb_78', 'emb_79', 'emb_80', 'emb_81', 'emb_82', 'emb_83', 'emb_84', 'emb_85', 'emb_86', 'emb_87', 'emb_88', 'emb_89', 'emb_90', 'emb_91', 'emb_92', 'emb_93', 'emb_94', 'emb_95', 'emb_96', 'emb_97', 'emb_98', 'emb_99', 'emb_100', 'emb_101', 'emb_102', 'emb_103', 'emb_104', 'emb_105', 'emb_106', 'emb_107', 'emb_108', 'emb_109', 'emb_110', 'emb_111', 'emb_112', 'emb_113', 'emb_114', 'emb_115', 'emb_116', 'emb_117', 'emb_118', 'emb_119', 'emb_120', 'emb_121', 'emb_122', 'emb_123', 'emb_124', 'emb_125', 'emb_126', 'emb_127', 'emb_128', 'emb_129', 'emb_130', 'emb_131', 'emb_132', 'emb_133', 'emb_134', 'emb_135', 'emb_136', 'emb_137', 'emb_138', 'emb_139', 'emb_140', 'emb_141', 'emb_142', 'emb_143', 'emb_144', 'emb_145', 'emb_146', 'emb_147', 'emb_148', 'emb_149', 'emb_150', 'emb_151', 'emb_152', 'emb_153', 'emb_154', 'emb_155', 'emb_156', 'emb_157', 'emb_158', 'emb_159', 'emb_160', 'emb_161', 'emb_162', 'emb_163', 'emb_164', 'emb_165', 'emb_166', 'emb_167', 'emb_168', 'emb_169', 'emb_170', 'emb_171', 'emb_172', 'emb_173', 'emb_174', 'emb_175', 'emb_176', 'emb_177', 'emb_178', 'emb_179', 'emb_180', 'emb_181', 'emb_182', 'emb_183', 'emb_184', 'emb_185', 'emb_186', 'emb_187', 'emb_188', 'emb_189', 'emb_190', 'emb_191', 'emb_192', 'emb_193', 'emb_194', 'emb_195', 'emb_196', 'emb_197', 'emb_198', 'emb_199', 'emb_200', 'emb_201', 'emb_202', 'emb_203', 'emb_204', 'emb_205', 'emb_206', 'emb_207', 'emb_208', 'emb_209', 'emb_210', 'emb_211', 'emb_212', 'emb_213', 'emb_214', 'emb_215', 'emb_216', 'emb_217', 'emb_218', 'emb_219', 'emb_220', 'emb_221', 'emb_222', 'emb_223', 'emb_224', 'emb_225', 'emb_226', 'emb_227', 'emb_228', 'emb_229', 'emb_230', 'emb_231', 'emb_232', 'emb_233', 'emb_234', 'emb_235', 'emb_236', 'emb_237', 'emb_238', 'emb_239', 'emb_240', 'emb_241', 'emb_242', 'emb_243', 'emb_244', 'emb_245', 'emb_246', 'emb_247', 'emb_248', 'emb_249', 'emb_250', 'emb_251', 'emb_252', 'emb_253', 'emb_254', 'emb_255', 'emb_256', 'emb_257', 'emb_258', 'emb_259', 'emb_260', 'emb_261', 'emb_262', 'emb_263', 'emb_264', 'emb_265', 'emb_266', 'emb_267', 'emb_268', 'emb_269', 'emb_270', 'emb_271', 'emb_272', 'emb_273', 'emb_274', 'emb_275', 'emb_276', 'emb_277', 'emb_278', 'emb_279', 'emb_280', 'emb_281', 'emb_282', 'emb_283', 'emb_284', 'emb_285', 'emb_286', 'emb_287', 'emb_288', 'emb_289', 'emb_290', 'emb_291', 'emb_292', 'emb_293', 'emb_294', 'emb_295', 'emb_296', 'emb_297', 'emb_298', 'emb_299', 'emb_300', 'emb_301', 'emb_302', 'emb_303', 'emb_304', 'emb_305', 'emb_306', 'emb_307', 'emb_308', 'emb_309', 'emb_310', 'emb_311', 'emb_312', 'emb_313', 'emb_314', 'emb_315', 'emb_316', 'emb_317', 'emb_318', 'emb_319', 'emb_320', 'emb_321', 'emb_322', 'emb_323', 'emb_324', 'emb_325', 'emb_326', 'emb_327', 'emb_328', 'emb_329', 'emb_330', 'emb_331', 'emb_332', 'emb_333', 'emb_334', 'emb_335', 'emb_336', 'emb_337', 'emb_338', 'emb_339', 'emb_340', 'emb_341', 'emb_342', 'emb_343', 'emb_344', 'emb_345', 'emb_346', 'emb_347', 'emb_348', 'emb_349', 'emb_350', 'emb_351', 'emb_352', 'emb_353', 'emb_354', 'emb_355', 'emb_356', 'emb_357', 'emb_358', 'emb_359', 'emb_360', 'emb_361', 'emb_362', 'emb_363', 'emb_364', 'emb_365', 'emb_366', 'emb_367', 'emb_368', 'emb_369', 'emb_370', 'emb_371', 'emb_372', 'emb_373', 'emb_374', 'emb_375', 'emb_376', 'emb_377', 'emb_378', 'emb_379', 'emb_380', 'emb_381', 'emb_382', 'emb_383', 'emb_384', 'emb_385', 'emb_386', 'emb_387', 'emb_388', 'emb_389', 'emb_390', 'emb_391', 'emb_392', 'emb_393', 'emb_394', 'emb_395', 'emb_396', 'emb_397', 'emb_398', 'emb_399', 'emb_400', 'emb_401', 'emb_402', 'emb_403', 'emb_404', 'emb_405', 'emb_406', 'emb_407', 'emb_408', 'emb_409', 'emb_410', 'emb_411', 'emb_412', 'emb_413', 'emb_414', 'emb_415', 'emb_416', 'emb_417', 'emb_418', 'emb_419', 'emb_420', 'emb_421', 'emb_422', 'emb_423', 'emb_424', 'emb_425', 'emb_426', 'emb_427', 'emb_428', 'emb_429', 'emb_430', 'emb_431', 'emb_432', 'emb_433', 'emb_434', 'emb_435', 'emb_436', 'emb_437', 'emb_438', 'emb_439', 'emb_440', 'emb_441', 'emb_442', 'emb_443', 'emb_444', 'emb_445', 'emb_446', 'emb_447', 'emb_448', 'emb_449', 'emb_450', 'emb_451', 'emb_452', 'emb_453', 'emb_454', 'emb_455', 'emb_456', 'emb_457', 'emb_458', 'emb_459', 'emb_460', 'emb_461', 'emb_462', 'emb_463', 'emb_464', 'emb_465', 'emb_466', 'emb_467', 'emb_468', 'emb_469', 'emb_470', 'emb_471', 'emb_472', 'emb_473', 'emb_474', 'emb_475', 'emb_476', 'emb_477', 'emb_478', 'emb_479', 'emb_480', 'emb_481', 'emb_482', 'emb_483', 'emb_484', 'emb_485', 'emb_486', 'emb_487', 'emb_488', 'emb_489', 'emb_490', 'emb_491', 'emb_492', 'emb_493', 'emb_494', 'emb_495', 'emb_496', 'emb_497', 'emb_498', 'emb_499', 'emb_500', 'emb_501', 'emb_502', 'emb_503', 'emb_504', 'emb_505', 'emb_506', 'emb_507', 'emb_508', 'emb_509', 'emb_510', 'emb_511']
[2025-10-12 22:03:28] First 5 rows:

,disease,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,emb_7,emb_8,...,emb_502,emb_503,emb_504,emb_505,emb_506,emb_507,emb_508,emb_509,emb_510,emb_511
GSM1051525,rheumatoid arthritis,0.000379,0.007248,-0.011952,-0.006601,-0.002977,0.001650,-0.002853,-0.006493,-0.003603,...,0.001855,0.004305,0.002511,0.002612,0.007929,-0.006192,-0.000926,-0.000606,0.011051,0.003112
GSM1051526,rheumatoid arthritis,-0.002986,0.003322,-0.002674,-0.010356,0.005399,0.009582,-0.007116,-0.010195,0.004752,...,0.002104,0.006323,0.003349,0.000850,0.008739,-0.000499,-0.003584,-0.003576,0.008540,-0.003069
GSM1051527,rheumatoid arthritis,-0.006568,0.003980,0.000052,-0.007087,-0.002809,0.004245,-0.003250,-0.004742,0.003934,...,0.005058,0.002357,0.002605,0.004585,0.003063,-0.010164,-0.005583,-0.003053,0.012815,0.001405
GSM1051528,rheumatoid arthritis,0.000215,0.009518,-0.009776,-0.007672,0.004302,0.010845,-0.001150,-0.007701,0.006775,...,0.004212,0.011965,0.009021,-0.004224,0.006240,0.002095,0.002774,-0.006467,-0.000980,-0.003478
GSM1051529,rheumatoid arthritis,-0.001178,0.006284,-0.006167,-0.007700,0.001529,0.008875,-0.003372,-0.004588,0.002095,...,0.004174,0.004763,0.007382,0.001549,0.006101,-0.000170,0.001114,-0.002347,0.005288,-0.000686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GSM1052209,Normal,-0.003765,0.008041,-0.006019,-0.009293,0.003222,0.009334,-0.003292,-0.012899,0.001117,...,0.002203,0.008307,0.006887,-0.001503,0.007390,0.002973,-0.002571,-0.001365,0.000916,0.001138
GSM1052210,Normal,-0.004615,-0.005707,-0.013385,0.008344,-0.020104,0.005249,-0.007903,0.005094,-0.011255,...,-0.016663,-0.014000,-0.005464,-0.007783,0.001713,-0.010014,-0.012169,0.010438,0.003982,0.016364
GSM1052211,Normal,-0.005845,0.007845,-0.008336,-0.003659,0.002398,0.004383,-0.005194,-0.007207,0.000569,...,0.000923,0.008879,0.010149,0.002801,0.009749,-0.000687,-0.004634,-0.000321,0.003844,0.001026
GSM1052212,Normal,-0.005973,0.000146,-0.000831,-0.002002,-0.001332,0.005437,-0.010735,-0.005272,-0.003169,...,0.004573,0.003191,0.005803,0.006951,0.006752,-0.002935,-0.005506,0.006975,0.013059,0.009616
GSM1052213,Normal,-0.003694,0.006270,0.002110,0.000326,0.005373,0.007281,-0.002606,-0.006328,-0.000102,...,0.000421,-0.003258,0.008460,0.007401,0.004312,-0.002361,-0.004746,0.001915,0.006294,0.007514

In [1]:
# Cell 4: Benchmark Ridge Classifiers with Different Training Sets
from simulacra.benchmark import (
    _log,
    run_benchmark_experiment,
    save_results_to_csv,
)

# Execute the benchmark experiment with multiple multipliers
all_results, summary_stats = run_benchmark_experiment('GSE42861', seeds=[42, 931782, 8481962], multipliers=(1, 2, 5))

# Save results to CSV
csv_path = save_results_to_csv(all_results, summary_stats, 'GSE42861', target_column='disease')

_log(f"CSV results saved to: {csv_path}")

# Display first few rows of CSV
import pandas as pd
results_df = pd.read_csv(csv_path)
_log(f"\nCSV Preview (first 10 rows):")
display(results_df)

[2025-10-14 15:35:52] Starting benchmark experiment for GSE42861 with seeds: [42, 931782, 8481962] and multipliers: (1.0, 2.0, 5.0)
[2025-10-14 15:35:52]
=== Running benchmark with seed 42 ===
[2025-10-14 15:35:52] Starting benchmark for GSE42861 with seed 42 and multipliers (1.0, 2.0, 5.0)...
[2025-10-14 15:35:52] Loading combined embeddings with target...
[2025-10-14 15:35:52] Split sizes - Train: 551, Test: 138
[2025-10-14 15:35:52] === Training Baseline Classifier (no augmentation) ===
[2025-10-14 15:35:52] === Training GaussianCopula Augmented Classifiers ===
[2025-10-14 15:35:52] Training GaussianCopula synthesizer (LONG OPERATION)...

C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:162: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:128: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

[2025-10-14 15:36:28] GaussianCopula synthesizer training completed in 35.87 seconds
[2025-10-14 15:36:28] Generating 5.0x synthetic data with GaussianCopula (LONG OPERATION)...
[2025-10-14 15:36:59] Synthetic data generation completed in 67.64 seconds
[2025-10-14 15:36:59] Testing GaussianCopula with 1.0x augmentation...
[2025-10-14 15:37:00] Testing GaussianCopula with 2.0x augmentation...
[2025-10-14 15:37:00] Testing GaussianCopula with 5.0x augmentation...
[2025-10-14 15:37:00] Total GaussianCopula processing time: 68.37 seconds
[2025-10-14 15:37:00] === Training CTGAN Augmented Classifiers ===
[2025-10-14 15:37:01] Training CTGAN synthesizer (LONG OPERATION)...

C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:162: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:128: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

PerformanceAlert: Using the CTGANSynthesizer on this data is not recommended. To model this data, CTGAN will generate a large number of columns.

Original Column Name   Est # of Columns (CTGAN)
disease                2
emb_0                  11
emb_1                  11
emb_2                  11
emb_3                  11
emb_4                  11
emb_5                  11
emb_6                  11
emb_7                  11
emb_8                  11
emb_9                  11
emb_10                 11
emb_11                 11
emb_12                 11
emb_13                 11
emb_14                 11
emb_15                 11
emb_16                 11
emb_17                 11
emb_18                 11
emb_19                 11
emb_20                 11
emb_21                 11
emb_22                 11
emb_23                 11
emb_24                 11
emb_25                 11
emb_26                 11
emb_27                 11
emb_28                 11
emb_29                 11
emb_30                 11
emb_31                 11
emb_32                 11
emb_33                 11
emb_34                 11
emb_35                 11
emb_36                 11
emb_37                 11
emb_38                 11
emb_39                 11
emb_40                 11
emb_41                 11
emb_42                 11
emb_43                 11
emb_44                 11
emb_45                 11
emb_46                 11
emb_47                 11
emb_48                 11
emb_49                 11
emb_50                 11
emb_51                 11
emb_52                 11
emb_53                 11
emb_54                 11
emb_55                 11
emb_56                 11
emb_57                 11
emb_58                 11
emb_59                 11
emb_60                 11
emb_61                 11
emb_62                 11
emb_63                 11
emb_64                 11
emb_65                 11
emb_66                 11
emb_67                 11
emb_68                 11
emb_69                 11
emb_70                 11
emb_71                 11
emb_72                 11
emb_73                 11
emb_74                 11
emb_75                 11
emb_76                 11
emb_77                 11
emb_78                 11
emb_79                 11
emb_80                 11
emb_81                 11
emb_82                 11
emb_83                 11
emb_84                 11
emb_85                 11
emb_86                 11
emb_87                 11
emb_88                 11
emb_89                 11
emb_90                 11
emb_91                 11
emb_92                 11
emb_93                 11
emb_94                 11
emb_95                 11
emb_96                 11
emb_97                 11
emb_98                 11
emb_99                 11
emb_100                11
emb_101                11
emb_102                11
emb_103                11
emb_104                11
emb_105                11
emb_106                11
emb_107                11
emb_108                11
emb_109                11
emb_110                11
emb_111                11
emb_112                11
emb_113                11
emb_114                11
emb_115                11
emb_116                11
emb_117                11
emb_118                11
emb_119                11
emb_120                11
emb_121                11
emb_122                11
emb_123                11
emb_124                11
emb_125                11
emb_126                11
emb_127                11
emb_128                11
emb_129                11
emb_130                11
emb_131                11
emb_132                11
emb_133                11
emb_134                11
emb_135                11
emb_136                11
emb_137                11
emb_138                11
emb_139                11
emb_140                11
emb_141                11
emb_142                11
emb_143                11
emb_144                11
emb_145                11
emb_146                11
emb_147                11
emb_148                11
emb_149                11
emb_150                11
emb_151                11
emb_152                11
emb_153                11
emb_154                11
emb_155                11
emb_156                11
emb_157                11
emb_158                11
emb_159                11
emb_160                11
emb_161                11
emb_162                11
emb_163                11
emb_164                11
emb_165                11
emb_166                11
emb_167                11
emb_168                11
emb_169                11
emb_170                11
emb_171                11
emb_172                11
emb_173                11
emb_174                11
emb_175                11
emb_176                11
emb_177                11
emb_178                11
emb_179                11
emb_180                11
emb_181                11
emb_182                11
emb_183                11
emb_184                11
emb_185                11
emb_186                11
emb_187                11
emb_188                11
emb_189                11
emb_190                11
emb_191                11
emb_192                11
emb_193                11
emb_194                11
emb_195                11
emb_196                11
emb_197                11
emb_198                11
emb_199                11
emb_200                11
emb_201                11
emb_202                11
emb_203                11
emb_204                11
emb_205                11
emb_206                11
emb_207                11
emb_208                11
emb_209                11
emb_210                11
emb_211                11
emb_212                11
emb_213                11
emb_214                11
emb_215                11
emb_216                11
emb_217                11
emb_218                11
emb_219                11
emb_220                11
emb_221                11
emb_222                11
emb_223                11
emb_224                11
emb_225                11
emb_226                11
emb_227                11
emb_228                11
emb_229                11
emb_230                11
emb_231                11
emb_232                11
emb_233                11
emb_234                11
emb_235                11
emb_236                11
emb_237                11
emb_238                11
emb_239                11
emb_240                11
emb_241                11
emb_242                11
emb_243                11
emb_244                11
emb_245                11
emb_246                11
emb_247                11
emb_248                11
emb_249                11
emb_250                11
emb_251                11
emb_252                11
emb_253                11
emb_254                11
emb_255                11
emb_256                11
emb_257                11
emb_258                11
emb_259                11
emb_260                11
emb_261                11
emb_262                11
emb_263                11
emb_264                11
emb_265                11
emb_266                11
emb_267                11
emb_268                11
emb_269                11
emb_270                11
emb_271                11
emb_272                11
emb_273                11
emb_274                11
emb_275                11
emb_276                11
emb_277                11
emb_278                11
emb_279                11
emb_280                11
emb_281                11
emb_282                11
emb_283                11
emb_284                11
emb_285                11
emb_286                11
emb_287                11
emb_288                11
emb_289                11
emb_290                11
emb_291                11
emb_292                11
emb_293                11
emb_294                11
emb_295                11
emb_296                11
emb_297                11
emb_298                11
emb_299                11
emb_300                11
emb_301                11
emb_302                11
emb_303                11
emb_304                11
emb_305                11
emb_306                11
emb_307                11
emb_308                11
emb_309                11
emb_310                11
emb_311                11
emb_312                11
emb_313                11
emb_314                11
emb_315                11
emb_316                11
emb_317                11
emb_318                11
emb_319                11
emb_320                11
emb_321                11
emb_322                11
emb_323                11
emb_324                11
emb_325                11
emb_326                11
emb_327                11
emb_328                11
emb_329                11
emb_330                11
emb_331                11
emb_332                11
emb_333                11
emb_334                11
emb_335                11
emb_336                11
emb_337                11
emb_338                11
emb_339                11
emb_340                11
emb_341                11
emb_342                11
emb_343                11
emb_344                11
emb_345                11
emb_346                11
emb_347                11
emb_348                11
emb_349                11
emb_350                11
emb_351                11
emb_352                11
emb_353                11
emb_354                11
emb_355                11
emb_356                11
emb_357                11
emb_358                11
emb_359                11
emb_360                11
emb_361                11
emb_362                11
emb_363                11
emb_364                11
emb_365                11
emb_366                11
emb_367                11
emb_368                11
emb_369                11
emb_370                11
emb_371                11
emb_372                11
emb_373                11
emb_374                11
emb_375                11
emb_376                11
emb_377                11
emb_378                11
emb_379                11
emb_380                11
emb_381                11
emb_382                11
emb_383                11
emb_384                11
emb_385                11
emb_386                11
emb_387                11
emb_388                11
emb_389                11
emb_390                11
emb_391                11
emb_392                11
emb_393                11
emb_394                11
emb_395                11
emb_396                11
emb_397                11
emb_398                11
emb_399                11
emb_400                11
emb_401                11
emb_402                11
emb_403                11
emb_404                11
emb_405                11
emb_406                11
emb_407                11
emb_408                11
emb_409                11
emb_410                11
emb_411                11
emb_412                11
emb_413                11
emb_414                11
emb_415                11
emb_416                11
emb_417                11
emb_418                11
emb_419                11
emb_420                11
emb_421                11
emb_422                11
emb_423                11
emb_424                11
emb_425                11
emb_426                11
emb_427                11
emb_428                11
emb_429                11
emb_430                11
emb_431                11
emb_432                11
emb_433                11
emb_434                11
emb_435                11
emb_436                11
emb_437                11
emb_438                11
emb_439                11
emb_440                11
emb_441                11
emb_442                11
emb_443                11
emb_444                11
emb_445                11
emb_446                11
emb_447                11
emb_448                11
emb_449                11
emb_450                11
emb_451                11
emb_452                11
emb_453                11
emb_454                11
emb_455                11
emb_456                11
emb_457                11
emb_458                11
emb_459                11
emb_460                11
emb_461                11
emb_462                11
emb_463                11
emb_464                11
emb_465                11
emb_466                11
emb_467                11
emb_468                11
emb_469                11
emb_470                11
emb_471                11
emb_472                11
emb_473                11
emb_474                11
emb_475                11
emb_476                11
emb_477                11
emb_478                11
emb_479                11
emb_480                11
emb_481                11
emb_482                11
emb_483                11
emb_484                11
emb_485                11
emb_486                11
emb_487                11
emb_488                11
emb_489                11
emb_490                11
emb_491                11
emb_492                11
emb_493                11
emb_494                11
emb_495                11
emb_496                11
emb_497                11
emb_498                11
emb_499                11
emb_500                11
emb_501                11
emb_502                11
emb_503                11
emb_504                11
emb_505                11
emb_506                11
emb_507                11
emb_508                11
emb_509                11
emb_510                11
emb_511                11

We recommend preprocessing discrete columns that can have many values, using 'update_transformers'. Or you may drop columns that are not necessary to model. (Exit this script using ctrl-C)
[2025-10-14 16:05:36] CTGAN synthesizer training completed in 1716.11 seconds
[2025-10-14 16:05:36] Generating 5.0x synthetic data with CTGAN (LONG OPERATION)...
[2025-10-14 16:06:11] Synthetic data generation completed in 1751.26 seconds
[2025-10-14 16:06:11] Testing CTGAN with 1.0x augmentation...
[2025-10-14 16:06:12] Testing CTGAN with 2.0x augmentation...
[2025-10-14 16:06:12] Testing CTGAN with 5.0x augmentation...
[2025-10-14 16:06:13] Total CTGAN processing time: 1752.51 seconds
[2025-10-14 16:06:13] === Training TVAE Augmented Classifiers ===
[2025-10-14 16:06:14] Training TVAE synthesizer (LONG OPERATION)...

C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:162: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:128: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

[2025-10-14 16:44:53] TVAE synthesizer training completed in 2320.00 seconds
[2025-10-14 16:44:53] Generating 5.0x synthetic data with TVAE (LONG OPERATION)...
[2025-10-14 16:45:31] Synthetic data generation completed in 2358.19 seconds
[2025-10-14 16:45:31] Testing TVAE with 1.0x augmentation...
[2025-10-14 16:45:31] Testing TVAE with 2.0x augmentation...
[2025-10-14 16:45:32] Testing TVAE with 5.0x augmentation...
[2025-10-14 16:45:32] Total TVAE processing time: 2359.43 seconds
[2025-10-14 16:45:32] Saving benchmark results to 2_poc_simulacra\GSE42861_benchmark_seed_42_mults_1-2-5.pkl...
[2025-10-14 16:45:35] Benchmark results saved successfully
[2025-10-14 16:45:35]
=== Running benchmark with seed 931782 ===
[2025-10-14 16:45:35] Starting benchmark for GSE42861 with seed 931782 and multipliers (1.0, 2.0, 5.0)...
[2025-10-14 16:45:35] Loading combined embeddings with target...
[2025-10-14 16:45:35] Split sizes - Train: 551, Test: 138
[2025-10-14 16:45:35] === Training Baseline Classifier (no augmentation) ===
[2025-10-14 16:45:35] === Training GaussianCopula Augmented Classifiers ===
[2025-10-14 16:45:36] Training GaussianCopula synthesizer (LONG OPERATION)...

C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:162: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:128: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

[2025-10-14 16:46:31] GaussianCopula synthesizer training completed in 55.61 seconds
[2025-10-14 16:46:31] Generating 5.0x synthetic data with GaussianCopula (LONG OPERATION)...
[2025-10-14 16:46:57] Synthetic data generation completed in 82.50 seconds
[2025-10-14 16:46:57] Testing GaussianCopula with 1.0x augmentation...
[2025-10-14 16:46:58] Testing GaussianCopula with 2.0x augmentation...
[2025-10-14 16:46:58] Testing GaussianCopula with 5.0x augmentation...
[2025-10-14 16:46:59] Total GaussianCopula processing time: 83.70 seconds
[2025-10-14 16:46:59] === Training CTGAN Augmented Classifiers ===
[2025-10-14 16:46:59] Training CTGAN synthesizer (LONG OPERATION)...

C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:162: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:128: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

PerformanceAlert: Using the CTGANSynthesizer on this data is not recommended. To model this data, CTGAN will generate a large number of columns.

Original Column Name   Est # of Columns (CTGAN)
disease                2
emb_0                  11
emb_1                  11
emb_2                  11
emb_3                  11
emb_4                  11
emb_5                  11
emb_6                  11
emb_7                  11
emb_8                  11
emb_9                  11
emb_10                 11
emb_11                 11
emb_12                 11
emb_13                 11
emb_14                 11
emb_15                 11
emb_16                 11
emb_17                 11
emb_18                 11
emb_19                 11
emb_20                 11
emb_21                 11
emb_22                 11
emb_23                 11
emb_24                 11
emb_25                 11
emb_26                 11
emb_27                 11
emb_28                 11
emb_29                 11
emb_30                 11
emb_31                 11
emb_32                 11
emb_33                 11
emb_34                 11
emb_35                 11
emb_36                 11
emb_37                 11
emb_38                 11
emb_39                 11
emb_40                 11
emb_41                 11
emb_42                 11
emb_43                 11
emb_44                 11
emb_45                 11
emb_46                 11
emb_47                 11
emb_48                 11
emb_49                 11
emb_50                 11
emb_51                 11
emb_52                 11
emb_53                 11
emb_54                 11
emb_55                 11
emb_56                 11
emb_57                 11
emb_58                 11
emb_59                 11
emb_60                 11
emb_61                 11
emb_62                 11
emb_63                 11
emb_64                 11
emb_65                 11
emb_66                 11
emb_67                 11
emb_68                 11
emb_69                 11
emb_70                 11
emb_71                 11
emb_72                 11
emb_73                 11
emb_74                 11
emb_75                 11
emb_76                 11
emb_77                 11
emb_78                 11
emb_79                 11
emb_80                 11
emb_81                 11
emb_82                 11
emb_83                 11
emb_84                 11
emb_85                 11
emb_86                 11
emb_87                 11
emb_88                 11
emb_89                 11
emb_90                 11
emb_91                 11
emb_92                 11
emb_93                 11
emb_94                 11
emb_95                 11
emb_96                 11
emb_97                 11
emb_98                 11
emb_99                 11
emb_100                11
emb_101                11
emb_102                11
emb_103                11
emb_104                11
emb_105                11
emb_106                11
emb_107                11
emb_108                11
emb_109                11
emb_110                11
emb_111                11
emb_112                11
emb_113                11
emb_114                11
emb_115                11
emb_116                11
emb_117                11
emb_118                11
emb_119                11
emb_120                11
emb_121                11
emb_122                11
emb_123                11
emb_124                11
emb_125                11
emb_126                11
emb_127                11
emb_128                11
emb_129                11
emb_130                11
emb_131                11
emb_132                11
emb_133                11
emb_134                11
emb_135                11
emb_136                11
emb_137                11
emb_138                11
emb_139                11
emb_140                11
emb_141                11
emb_142                11
emb_143                11
emb_144                11
emb_145                11
emb_146                11
emb_147                11
emb_148                11
emb_149                11
emb_150                11
emb_151                11
emb_152                11
emb_153                11
emb_154                11
emb_155                11
emb_156                11
emb_157                11
emb_158                11
emb_159                11
emb_160                11
emb_161                11
emb_162                11
emb_163                11
emb_164                11
emb_165                11
emb_166                11
emb_167                11
emb_168                11
emb_169                11
emb_170                11
emb_171                11
emb_172                11
emb_173                11
emb_174                11
emb_175                11
emb_176                11
emb_177                11
emb_178                11
emb_179                11
emb_180                11
emb_181                11
emb_182                11
emb_183                11
emb_184                11
emb_185                11
emb_186                11
emb_187                11
emb_188                11
emb_189                11
emb_190                11
emb_191                11
emb_192                11
emb_193                11
emb_194                11
emb_195                11
emb_196                11
emb_197                11
emb_198                11
emb_199                11
emb_200                11
emb_201                11
emb_202                11
emb_203                11
emb_204                11
emb_205                11
emb_206                11
emb_207                11
emb_208                11
emb_209                11
emb_210                11
emb_211                11
emb_212                11
emb_213                11
emb_214                11
emb_215                11
emb_216                11
emb_217                11
emb_218                11
emb_219                11
emb_220                11
emb_221                11
emb_222                11
emb_223                11
emb_224                11
emb_225                11
emb_226                11
emb_227                11
emb_228                11
emb_229                11
emb_230                11
emb_231                11
emb_232                11
emb_233                11
emb_234                11
emb_235                11
emb_236                11
emb_237                11
emb_238                11
emb_239                11
emb_240                11
emb_241                11
emb_242                11
emb_243                11
emb_244                11
emb_245                11
emb_246                11
emb_247                11
emb_248                11
emb_249                11
emb_250                11
emb_251                11
emb_252                11
emb_253                11
emb_254                11
emb_255                11
emb_256                11
emb_257                11
emb_258                11
emb_259                11
emb_260                11
emb_261                11
emb_262                11
emb_263                11
emb_264                11
emb_265                11
emb_266                11
emb_267                11
emb_268                11
emb_269                11
emb_270                11
emb_271                11
emb_272                11
emb_273                11
emb_274                11
emb_275                11
emb_276                11
emb_277                11
emb_278                11
emb_279                11
emb_280                11
emb_281                11
emb_282                11
emb_283                11
emb_284                11
emb_285                11
emb_286                11
emb_287                11
emb_288                11
emb_289                11
emb_290                11
emb_291                11
emb_292                11
emb_293                11
emb_294                11
emb_295                11
emb_296                11
emb_297                11
emb_298                11
emb_299                11
emb_300                11
emb_301                11
emb_302                11
emb_303                11
emb_304                11
emb_305                11
emb_306                11
emb_307                11
emb_308                11
emb_309                11
emb_310                11
emb_311                11
emb_312                11
emb_313                11
emb_314                11
emb_315                11
emb_316                11
emb_317                11
emb_318                11
emb_319                11
emb_320                11
emb_321                11
emb_322                11
emb_323                11
emb_324                11
emb_325                11
emb_326                11
emb_327                11
emb_328                11
emb_329                11
emb_330                11
emb_331                11
emb_332                11
emb_333                11
emb_334                11
emb_335                11
emb_336                11
emb_337                11
emb_338                11
emb_339                11
emb_340                11
emb_341                11
emb_342                11
emb_343                11
emb_344                11
emb_345                11
emb_346                11
emb_347                11
emb_348                11
emb_349                11
emb_350                11
emb_351                11
emb_352                11
emb_353                11
emb_354                11
emb_355                11
emb_356                11
emb_357                11
emb_358                11
emb_359                11
emb_360                11
emb_361                11
emb_362                11
emb_363                11
emb_364                11
emb_365                11
emb_366                11
emb_367                11
emb_368                11
emb_369                11
emb_370                11
emb_371                11
emb_372                11
emb_373                11
emb_374                11
emb_375                11
emb_376                11
emb_377                11
emb_378                11
emb_379                11
emb_380                11
emb_381                11
emb_382                11
emb_383                11
emb_384                11
emb_385                11
emb_386                11
emb_387                11
emb_388                11
emb_389                11
emb_390                11
emb_391                11
emb_392                11
emb_393                11
emb_394                11
emb_395                11
emb_396                11
emb_397                11
emb_398                11
emb_399                11
emb_400                11
emb_401                11
emb_402                11
emb_403                11
emb_404                11
emb_405                11
emb_406                11
emb_407                11
emb_408                11
emb_409                11
emb_410                11
emb_411                11
emb_412                11
emb_413                11
emb_414                11
emb_415                11
emb_416                11
emb_417                11
emb_418                11
emb_419                11
emb_420                11
emb_421                11
emb_422                11
emb_423                11
emb_424                11
emb_425                11
emb_426                11
emb_427                11
emb_428                11
emb_429                11
emb_430                11
emb_431                11
emb_432                11
emb_433                11
emb_434                11
emb_435                11
emb_436                11
emb_437                11
emb_438                11
emb_439                11
emb_440                11
emb_441                11
emb_442                11
emb_443                11
emb_444                11
emb_445                11
emb_446                11
emb_447                11
emb_448                11
emb_449                11
emb_450                11
emb_451                11
emb_452                11
emb_453                11
emb_454                11
emb_455                11
emb_456                11
emb_457                11
emb_458                11
emb_459                11
emb_460                11
emb_461                11
emb_462                11
emb_463                11
emb_464                11
emb_465                11
emb_466                11
emb_467                11
emb_468                11
emb_469                11
emb_470                11
emb_471                11
emb_472                11
emb_473                11
emb_474                11
emb_475                11
emb_476                11
emb_477                11
emb_478                11
emb_479                11
emb_480                11
emb_481                11
emb_482                11
emb_483                11
emb_484                11
emb_485                11
emb_486                11
emb_487                11
emb_488                11
emb_489                11
emb_490                11
emb_491                11
emb_492                11
emb_493                11
emb_494                11
emb_495                11
emb_496                11
emb_497                11
emb_498                11
emb_499                11
emb_500                11
emb_501                11
emb_502                11
emb_503                11
emb_504                11
emb_505                11
emb_506                11
emb_507                11
emb_508                11
emb_509                11
emb_510                11
emb_511                11

We recommend preprocessing discrete columns that can have many values, using 'update_transformers'. Or you may drop columns that are not necessary to model. (Exit this script using ctrl-C)
[2025-10-14 17:06:54] CTGAN synthesizer training completed in 1195.80 seconds
[2025-10-14 17:06:54] Generating 5.0x synthetic data with CTGAN (LONG OPERATION)...
[2025-10-14 17:07:51] Synthetic data generation completed in 1252.16 seconds
[2025-10-14 17:07:51] Testing CTGAN with 1.0x augmentation...
[2025-10-14 17:07:51] Testing CTGAN with 2.0x augmentation...
[2025-10-14 17:07:52] Testing CTGAN with 5.0x augmentation...
[2025-10-14 17:07:52] Total CTGAN processing time: 1253.82 seconds
[2025-10-14 17:07:52] === Training TVAE Augmented Classifiers ===
[2025-10-14 17:07:54] Training TVAE synthesizer (LONG OPERATION)...

C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:162: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:128: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

[2025-10-14 17:47:24] TVAE synthesizer training completed in 2371.64 seconds
[2025-10-14 17:47:24] Generating 5.0x synthetic data with TVAE (LONG OPERATION)...
[2025-10-14 17:48:04] Synthetic data generation completed in 2411.39 seconds
[2025-10-14 17:48:04] Testing TVAE with 1.0x augmentation...
[2025-10-14 17:48:04] Testing TVAE with 2.0x augmentation...
[2025-10-14 17:48:04] Testing TVAE with 5.0x augmentation...
[2025-10-14 17:48:05] Total TVAE processing time: 2412.66 seconds
[2025-10-14 17:48:05] Saving benchmark results to 2_poc_simulacra\GSE42861_benchmark_seed_931782_mults_1-2-5.pkl...
[2025-10-14 17:48:12] Benchmark results saved successfully
[2025-10-14 17:48:12]
=== Running benchmark with seed 8481962 ===
[2025-10-14 17:48:12] Starting benchmark for GSE42861 with seed 8481962 and multipliers (1.0, 2.0, 5.0)...
[2025-10-14 17:48:12] Loading combined embeddings with target...
[2025-10-14 17:48:12] Split sizes - Train: 551, Test: 138
[2025-10-14 17:48:12] === Training Baseline Classifier (no augmentation) ===
[2025-10-14 17:48:12] === Training GaussianCopula Augmented Classifiers ===
[2025-10-14 17:48:14] Training GaussianCopula synthesizer (LONG OPERATION)...

C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:162: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:128: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

[2025-10-14 17:49:45] GaussianCopula synthesizer training completed in 93.07 seconds
[2025-10-14 17:49:45] Generating 5.0x synthetic data with GaussianCopula (LONG OPERATION)...
[2025-10-14 17:50:28] Synthetic data generation completed in 135.65 seconds
[2025-10-14 17:50:28] Testing GaussianCopula with 1.0x augmentation...
[2025-10-14 17:50:28] Testing GaussianCopula with 2.0x augmentation...
[2025-10-14 17:50:28] Testing GaussianCopula with 5.0x augmentation...
[2025-10-14 17:50:29] Total GaussianCopula processing time: 136.75 seconds
[2025-10-14 17:50:29] === Training CTGAN Augmented Classifiers ===
[2025-10-14 17:50:30] Training CTGAN synthesizer (LONG OPERATION)...

C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:162: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:128: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

PerformanceAlert: Using the CTGANSynthesizer on this data is not recommended. To model this data, CTGAN will generate a large number of columns.

Original Column Name   Est # of Columns (CTGAN)
disease                2
emb_0                  11
emb_1                  11
emb_2                  11
emb_3                  11
emb_4                  11
emb_5                  11
emb_6                  11
emb_7                  11
emb_8                  11
emb_9                  11
emb_10                 11
emb_11                 11
emb_12                 11
emb_13                 11
emb_14                 11
emb_15                 11
emb_16                 11
emb_17                 11
emb_18                 11
emb_19                 11
emb_20                 11
emb_21                 11
emb_22                 11
emb_23                 11
emb_24                 11
emb_25                 11
emb_26                 11
emb_27                 11
emb_28                 11
emb_29                 11
emb_30                 11
emb_31                 11
emb_32                 11
emb_33                 11
emb_34                 11
emb_35                 11
emb_36                 11
emb_37                 11
emb_38                 11
emb_39                 11
emb_40                 11
emb_41                 11
emb_42                 11
emb_43                 11
emb_44                 11
emb_45                 11
emb_46                 11
emb_47                 11
emb_48                 11
emb_49                 11
emb_50                 11
emb_51                 11
emb_52                 11
emb_53                 11
emb_54                 11
emb_55                 11
emb_56                 11
emb_57                 11
emb_58                 11
emb_59                 11
emb_60                 11
emb_61                 11
emb_62                 11
emb_63                 11
emb_64                 11
emb_65                 11
emb_66                 11
emb_67                 11
emb_68                 11
emb_69                 11
emb_70                 11
emb_71                 11
emb_72                 11
emb_73                 11
emb_74                 11
emb_75                 11
emb_76                 11
emb_77                 11
emb_78                 11
emb_79                 11
emb_80                 11
emb_81                 11
emb_82                 11
emb_83                 11
emb_84                 11
emb_85                 11
emb_86                 11
emb_87                 11
emb_88                 11
emb_89                 11
emb_90                 11
emb_91                 11
emb_92                 11
emb_93                 11
emb_94                 11
emb_95                 11
emb_96                 11
emb_97                 11
emb_98                 11
emb_99                 11
emb_100                11
emb_101                11
emb_102                11
emb_103                11
emb_104                11
emb_105                11
emb_106                11
emb_107                11
emb_108                11
emb_109                11
emb_110                11
emb_111                11
emb_112                11
emb_113                11
emb_114                11
emb_115                11
emb_116                11
emb_117                11
emb_118                11
emb_119                11
emb_120                11
emb_121                11
emb_122                11
emb_123                11
emb_124                11
emb_125                11
emb_126                11
emb_127                11
emb_128                11
emb_129                11
emb_130                11
emb_131                11
emb_132                11
emb_133                11
emb_134                11
emb_135                11
emb_136                11
emb_137                11
emb_138                11
emb_139                11
emb_140                11
emb_141                11
emb_142                11
emb_143                11
emb_144                11
emb_145                11
emb_146                11
emb_147                11
emb_148                11
emb_149                11
emb_150                11
emb_151                11
emb_152                11
emb_153                11
emb_154                11
emb_155                11
emb_156                11
emb_157                11
emb_158                11
emb_159                11
emb_160                11
emb_161                11
emb_162                11
emb_163                11
emb_164                11
emb_165                11
emb_166                11
emb_167                11
emb_168                11
emb_169                11
emb_170                11
emb_171                11
emb_172                11
emb_173                11
emb_174                11
emb_175                11
emb_176                11
emb_177                11
emb_178                11
emb_179                11
emb_180                11
emb_181                11
emb_182                11
emb_183                11
emb_184                11
emb_185                11
emb_186                11
emb_187                11
emb_188                11
emb_189                11
emb_190                11
emb_191                11
emb_192                11
emb_193                11
emb_194                11
emb_195                11
emb_196                11
emb_197                11
emb_198                11
emb_199                11
emb_200                11
emb_201                11
emb_202                11
emb_203                11
emb_204                11
emb_205                11
emb_206                11
emb_207                11
emb_208                11
emb_209                11
emb_210                11
emb_211                11
emb_212                11
emb_213                11
emb_214                11
emb_215                11
emb_216                11
emb_217                11
emb_218                11
emb_219                11
emb_220                11
emb_221                11
emb_222                11
emb_223                11
emb_224                11
emb_225                11
emb_226                11
emb_227                11
emb_228                11
emb_229                11
emb_230                11
emb_231                11
emb_232                11
emb_233                11
emb_234                11
emb_235                11
emb_236                11
emb_237                11
emb_238                11
emb_239                11
emb_240                11
emb_241                11
emb_242                11
emb_243                11
emb_244                11
emb_245                11
emb_246                11
emb_247                11
emb_248                11
emb_249                11
emb_250                11
emb_251                11
emb_252                11
emb_253                11
emb_254                11
emb_255                11
emb_256                11
emb_257                11
emb_258                11
emb_259                11
emb_260                11
emb_261                11
emb_262                11
emb_263                11
emb_264                11
emb_265                11
emb_266                11
emb_267                11
emb_268                11
emb_269                11
emb_270                11
emb_271                11
emb_272                11
emb_273                11
emb_274                11
emb_275                11
emb_276                11
emb_277                11
emb_278                11
emb_279                11
emb_280                11
emb_281                11
emb_282                11
emb_283                11
emb_284                11
emb_285                11
emb_286                11
emb_287                11
emb_288                11
emb_289                11
emb_290                11
emb_291                11
emb_292                11
emb_293                11
emb_294                11
emb_295                11
emb_296                11
emb_297                11
emb_298                11
emb_299                11
emb_300                11
emb_301                11
emb_302                11
emb_303                11
emb_304                11
emb_305                11
emb_306                11
emb_307                11
emb_308                11
emb_309                11
emb_310                11
emb_311                11
emb_312                11
emb_313                11
emb_314                11
emb_315                11
emb_316                11
emb_317                11
emb_318                11
emb_319                11
emb_320                11
emb_321                11
emb_322                11
emb_323                11
emb_324                11
emb_325                11
emb_326                11
emb_327                11
emb_328                11
emb_329                11
emb_330                11
emb_331                11
emb_332                11
emb_333                11
emb_334                11
emb_335                11
emb_336                11
emb_337                11
emb_338                11
emb_339                11
emb_340                11
emb_341                11
emb_342                11
emb_343                11
emb_344                11
emb_345                11
emb_346                11
emb_347                11
emb_348                11
emb_349                11
emb_350                11
emb_351                11
emb_352                11
emb_353                11
emb_354                11
emb_355                11
emb_356                11
emb_357                11
emb_358                11
emb_359                11
emb_360                11
emb_361                11
emb_362                11
emb_363                11
emb_364                11
emb_365                11
emb_366                11
emb_367                11
emb_368                11
emb_369                11
emb_370                11
emb_371                11
emb_372                11
emb_373                11
emb_374                11
emb_375                11
emb_376                11
emb_377                11
emb_378                11
emb_379                11
emb_380                11
emb_381                11
emb_382                11
emb_383                11
emb_384                11
emb_385                11
emb_386                11
emb_387                11
emb_388                11
emb_389                11
emb_390                11
emb_391                11
emb_392                11
emb_393                11
emb_394                11
emb_395                11
emb_396                11
emb_397                11
emb_398                11
emb_399                11
emb_400                11
emb_401                11
emb_402                11
emb_403                11
emb_404                11
emb_405                11
emb_406                11
emb_407                11
emb_408                11
emb_409                11
emb_410                11
emb_411                11
emb_412                11
emb_413                11
emb_414                11
emb_415                11
emb_416                11
emb_417                11
emb_418                11
emb_419                11
emb_420                11
emb_421                11
emb_422                11
emb_423                11
emb_424                11
emb_425                11
emb_426                11
emb_427                11
emb_428                11
emb_429                11
emb_430                11
emb_431                11
emb_432                11
emb_433                11
emb_434                11
emb_435                11
emb_436                11
emb_437                11
emb_438                11
emb_439                11
emb_440                11
emb_441                11
emb_442                11
emb_443                11
emb_444                11
emb_445                11
emb_446                11
emb_447                11
emb_448                11
emb_449                11
emb_450                11
emb_451                11
emb_452                11
emb_453                11
emb_454                11
emb_455                11
emb_456                11
emb_457                11
emb_458                11
emb_459                11
emb_460                11
emb_461                11
emb_462                11
emb_463                11
emb_464                11
emb_465                11
emb_466                11
emb_467                11
emb_468                11
emb_469                11
emb_470                11
emb_471                11
emb_472                11
emb_473                11
emb_474                11
emb_475                11
emb_476                11
emb_477                11
emb_478                11
emb_479                11
emb_480                11
emb_481                11
emb_482                11
emb_483                11
emb_484                11
emb_485                11
emb_486                11
emb_487                11
emb_488                11
emb_489                11
emb_490                11
emb_491                11
emb_492                11
emb_493                11
emb_494                11
emb_495                11
emb_496                11
emb_497                11
emb_498                11
emb_499                11
emb_500                11
emb_501                11
emb_502                11
emb_503                11
emb_504                11
emb_505                11
emb_506                11
emb_507                11
emb_508                11
emb_509                11
emb_510                11
emb_511                11

We recommend preprocessing discrete columns that can have many values, using 'update_transformers'. Or you may drop columns that are not necessary to model. (Exit this script using ctrl-C)
[2025-10-14 18:21:18] CTGAN synthesizer training completed in 1849.23 seconds
[2025-10-14 18:21:18] Generating 5.0x synthetic data with CTGAN (LONG OPERATION)...
[2025-10-14 18:22:07] Synthetic data generation completed in 1898.12 seconds
[2025-10-14 18:22:07] Testing CTGAN with 1.0x augmentation...
[2025-10-14 18:22:08] Testing CTGAN with 2.0x augmentation...
[2025-10-14 18:22:08] Testing CTGAN with 5.0x augmentation...
[2025-10-14 18:22:08] Total CTGAN processing time: 1899.12 seconds
[2025-10-14 18:22:08] === Training TVAE Augmented Classifiers ===
[2025-10-14 18:22:09] Training TVAE synthesizer (LONG OPERATION)...

C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:162: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:128: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

[2025-10-14 19:15:02] TVAE synthesizer training completed in 3173.77 seconds
[2025-10-14 19:15:02] Generating 5.0x synthetic data with TVAE (LONG OPERATION)...
[2025-10-14 19:15:57] Synthetic data generation completed in 3228.67 seconds
[2025-10-14 19:15:57] Testing TVAE with 1.0x augmentation...
[2025-10-14 19:15:58] Testing TVAE with 2.0x augmentation...
[2025-10-14 19:15:58] Testing TVAE with 5.0x augmentation...
[2025-10-14 19:15:59] Total TVAE processing time: 3230.90 seconds
[2025-10-14 19:15:59] Saving benchmark results to 2_poc_simulacra\GSE42861_benchmark_seed_8481962_mults_1-2-5.pkl...
[2025-10-14 19:16:07] Benchmark results saved successfully
[2025-10-14 19:16:07]
=== Computing Statistics Across Seeds ===
[2025-10-14 19:16:07]
=== BENCHMARK RESULTS SUMMARY ===
[2025-10-14 19:16:07] Method                Accuracy (mean ± std)    F1 Macro (mean ± std)
[2025-10-14 19:16:07] ----------------------------------------------------------------------
[2025-10-14 19:16:07] baseline             0.7415 ± 0.0385        0.7412 ± 0.0383
[2025-10-14 19:16:07] CTGAN_1x             0.7391 ± 0.0355        0.7388 ± 0.0354
[2025-10-14 19:16:07] CTGAN_2x             0.7560 ± 0.0326        0.7558 ± 0.0324
[2025-10-14 19:16:07] CTGAN_5x             0.7585 ± 0.0304        0.7580 ± 0.0306
[2025-10-14 19:16:07] GaussianCopula_1x    0.7391 ± 0.0542        0.7386 ± 0.0542
[2025-10-14 19:16:07] GaussianCopula_2x    0.7415 ± 0.0503        0.7412 ± 0.0501
[2025-10-14 19:16:07] GaussianCopula_5x    0.7343 ± 0.0503        0.7338 ± 0.0501
[2025-10-14 19:16:07] TVAE_1x              0.7367 ± 0.0357        0.7364 ± 0.0357
[2025-10-14 19:16:07] TVAE_2x              0.7657 ± 0.0224        0.7652 ± 0.0227
[2025-10-14 19:16:07] TVAE_5x              0.7512 ± 0.0090        0.7507 ± 0.0096
[2025-10-14 19:16:07] Saving results to CSV file...
[2025-10-14 19:16:07] Results saved to 2_poc_simulacra\GSE42861_benchmark_results.csv
[2025-10-14 19:16:07] CSV results saved to: 2_poc_simulacra\GSE42861_benchmark_results.csv
[2025-10-14 19:16:07]
CSV Preview (first 10 rows):

,accession,dnam_path,metadata_path,target_column,seed,method,multiplier,accuracy,f1_macro,test_size,train_size,timestamp
0,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,42,baseline,NaN,0.789855,0.789313,138.0,551.0,2025-10-14 19:16:07
1,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,42,GaussianCopula_1x,1.0,0.811594,0.810959,138.0,1102.0,2025-10-14 19:16:07
2,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,42,GaussianCopula_2x,2.0,0.811594,0.810959,138.0,1653.0,2025-10-14 19:16:07
3,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,42,GaussianCopula_5x,5.0,0.804348,0.803512,138.0,3306.0,2025-10-14 19:16:07
4,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,42,CTGAN_1x,1.0,0.782609,0.782197,138.0,1102.0,2025-10-14 19:16:07
5,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,42,CTGAN_2x,2.0,0.797101,0.796717,138.0,1653.0,2025-10-14 19:16:07
6,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,42,CTGAN_5x,5.0,0.789855,0.789756,138.0,3306.0,2025-10-14 19:16:07
7,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,42,TVAE_1x,1.0,0.782609,0.782563,138.0,1102.0,2025-10-14 19:16:07
8,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,42,TVAE_2x,2.0,0.797101,0.796931,138.0,1653.0,2025-10-14 19:16:07
9,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,42,TVAE_5x,5.0,0.760870,0.760857,138.0,3306.0,2025-10-14 19:16:07
10,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,931782,baseline,NaN,0.695652,0.695588,138.0,551.0,2025-10-14 19:16:07
11,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,931782,GaussianCopula_1x,1.0,0.681159,0.680556,138.0,1102.0,2025-10-14 19:16:07
12,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,931782,GaussianCopula_2x,2.0,0.695652,0.695588,138.0,1653.0,2025-10-14 19:16:07
13,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,931782,GaussianCopula_5x,5.0,0.688406,0.688258,138.0,3306.0,2025-10-14 19:16:07
14,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,931782,CTGAN_1x,1.0,0.695652,0.695588,138.0,1102.0,2025-10-14 19:16:07
15,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,931782,CTGAN_2x,2.0,0.717391,0.717376,138.0,1653.0,2025-10-14 19:16:07
16,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,931782,CTGAN_5x,5.0,0.717391,0.716662,138.0,3306.0,2025-10-14 19:16:07
17,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,931782,TVAE_1x,1.0,0.695652,0.695588,138.0,1102.0,2025-10-14 19:16:07
18,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,931782,TVAE_2x,2.0,0.753623,0.753416,138.0,1653.0,2025-10-14 19:16:07
19,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,931782,TVAE_5x,5.0,0.739130,0.737753,138.0,3306.0,2025-10-14 19:16:07
20,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,8481962,baseline,NaN,0.739130,0.738636,138.0,551.0,2025-10-14 19:16:07
21,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,8481962,GaussianCopula_1x,1.0,0.724638,0.724406,138.0,1102.0,2025-10-14 19:16:07
22,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,8481962,GaussianCopula_2x,2.0,0.717391,0.717020,138.0,1653.0,2025-10-14 19:16:07
23,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,8481962,GaussianCopula_5x,5.0,0.710145,0.709596,138.0,3306.0,2025-10-14 19:16:07
24,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,8481962,CTGAN_1x,1.0,0.739130,0.738636,138.0,1102.0,2025-10-14 19:16:07
25,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,8481962,CTGAN_2x,2.0,0.753623,0.753157,138.0,1653.0,2025-10-14 19:16:07
26,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,8481962,CTGAN_5x,5.0,0.768116,0.767677,138.0,3306.0,2025-10-14 19:16:07
27,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,8481962,TVAE_1x,1.0,0.731884,0.731192,138.0,1102.0,2025-10-14 19:16:07
28,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,8481962,TVAE_2x,2.0,0.746377,0.745293,138.0,1653.0,2025-10-14 19:16:07
29,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,8481962,TVAE_5x,5.0,0.753623,0.753416,138.0,3306.0,2025-10-14 19:16:07
30,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,SUMMARY,baseline,NaN,0.741546,0.741179,NaN,NaN,2025-10-14 19:16:07
31,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,SUMMARY,CTGAN_1x,NaN,0.739130,0.738807,NaN,NaN,2025-10-14 19:16:07
32,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,SUMMARY,CTGAN_2x,NaN,0.756039,0.755750,NaN,NaN,2025-10-14 19:16:07
33,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,SUMMARY,CTGAN_5x,NaN,0.758454,0.758032,NaN,NaN,2025-10-14 19:16:07
34,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,SUMMARY,GaussianCopula_1x,NaN,0.739130,0.738640,NaN,NaN,2025-10-14 19:16:07
35,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,SUMMARY,GaussianCopula_2x,NaN,0.741546,0.741189,NaN,NaN,2025-10-14 19:16:07
36,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,SUMMARY,GaussianCopula_5x,NaN,0.734300,0.733789,NaN,NaN,2025-10-14 19:16:07
37,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,SUMMARY,TVAE_1x,NaN,0.736715,0.736448,NaN,NaN,2025-10-14 19:16:07
38,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,SUMMARY,TVAE_2x,NaN,0.765700,0.765213,NaN,NaN,2025-10-14 19:16:07
39,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,SUMMARY,TVAE_5x,NaN,0.751208,0.750675,NaN,NaN,2025-10-14 19:16:07

In [4]:
%load_ext autoreload
%autoreload 2
# Cell 5: Repeat benchmark with more multipliers: 
# Ridge Classifiers with Different Training Sets
from simulacra.benchmark import (
    _log,
    run_benchmark_experiment,
    save_results_to_csv,
)

# Execute the benchmark experiment with multiple multipliers
all_results, summary_stats = run_benchmark_experiment('GSE42861', seeds=[42, 931782, 8481962], multipliers=(0.2, 0.5, 10))

# Save results to CSV
csv_path = save_results_to_csv(all_results, summary_stats, 'GSE42861', target_column='disease')

_log(f"CSV results saved to: {csv_path}")

# Display first few rows of CSV
import pandas as pd
results_df = pd.read_csv(csv_path)
_log(f"\nCSV Preview (first 10 rows):")
display(results_df)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
[2025-10-14 23:44:52] Starting benchmark experiment for GSE42861 with seeds: [42, 931782, 8481962] and multipliers: (0.2, 0.5, 10.0)
[2025-10-14 23:44:52]
=== Running benchmark with seed 42 ===
[2025-10-14 23:44:52] Starting benchmark for GSE42861 with seed 42 and multipliers (0.2, 0.5, 10.0)...
[2025-10-14 23:44:52] CUDA usage: Enabled
[2025-10-14 23:44:52] Loading combined embeddings with target...
[2025-10-14 23:44:52] Split sizes - Train: 551, Test: 138
[2025-10-14 23:44:52] === Training Baseline Classifier (no augmentation) ===
[2025-10-14 23:44:53] === Training GaussianCopula Augmented Classifiers ===
[2025-10-14 23:44:53] Creating new synthesizer for GaussianCopula...
[2025-10-14 23:44:53] Creating metadata for GaussianCopula...
[2025-10-14 23:44:53] Metadata saved to 2_poc_simulacra\GSE42861_GaussianCopula_metadata_seed_42.json
[2025-10-14 23:44:53] Training GaussianCopula synthesizer (LONG OPERATION)...

C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:162: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:128: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

[2025-10-14 23:47:33] Saving trained synthesizer to 2_poc_simulacra\GSE42861_GaussianCopula_synthesizer_seed_42.pkl
[2025-10-14 23:47:34] Synthesizer saved successfully
[2025-10-14 23:47:34] GaussianCopula synthesizer training completed in 161.41 seconds
[2025-10-14 23:47:34] Generating 10.0x synthetic data with GaussianCopula (LONG OPERATION)...
[2025-10-14 23:48:27] Synthetic data generation completed in 214.14 seconds
[2025-10-14 23:48:27] Testing GaussianCopula with 0.2x augmentation...
[2025-10-14 23:48:27] Testing GaussianCopula with 0.5x augmentation...
[2025-10-14 23:48:27] Testing GaussianCopula with 10.0x augmentation...
[2025-10-14 23:48:28] Total GaussianCopula processing time: 215.26 seconds
[2025-10-14 23:48:28] === Training CTGAN Augmented Classifiers ===
[2025-10-14 23:48:28] Creating new synthesizer for CTGAN...
[2025-10-14 23:48:28] Creating metadata for CTGAN...
[2025-10-14 23:48:29] Metadata saved to 2_poc_simulacra\GSE42861_CTGAN_metadata_seed_42.json
[2025-10-14 23:48:29] Training CTGAN synthesizer (LONG OPERATION)...
[2025-10-14 23:48:29] Using CUDA acceleration for CTGAN

C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:162: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:128: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

PerformanceAlert: Using the CTGANSynthesizer on this data is not recommended. To model this data, CTGAN will generate a large number of columns.

Original Column Name   Est # of Columns (CTGAN)
disease                2
emb_0                  11
emb_1                  11
emb_2                  11
emb_3                  11
emb_4                  11
emb_5                  11
emb_6                  11
emb_7                  11
emb_8                  11
emb_9                  11
emb_10                 11
emb_11                 11
emb_12                 11
emb_13                 11
emb_14                 11
emb_15                 11
emb_16                 11
emb_17                 11
emb_18                 11
emb_19                 11
emb_20                 11
emb_21                 11
emb_22                 11
emb_23                 11
emb_24                 11
emb_25                 11
emb_26                 11
emb_27                 11
emb_28                 11
emb_29                 11
emb_30                 11
emb_31                 11
emb_32                 11
emb_33                 11
emb_34                 11
emb_35                 11
emb_36                 11
emb_37                 11
emb_38                 11
emb_39                 11
emb_40                 11
emb_41                 11
emb_42                 11
emb_43                 11
emb_44                 11
emb_45                 11
emb_46                 11
emb_47                 11
emb_48                 11
emb_49                 11
emb_50                 11
emb_51                 11
emb_52                 11
emb_53                 11
emb_54                 11
emb_55                 11
emb_56                 11
emb_57                 11
emb_58                 11
emb_59                 11
emb_60                 11
emb_61                 11
emb_62                 11
emb_63                 11
emb_64                 11
emb_65                 11
emb_66                 11
emb_67                 11
emb_68                 11
emb_69                 11
emb_70                 11
emb_71                 11
emb_72                 11
emb_73                 11
emb_74                 11
emb_75                 11
emb_76                 11
emb_77                 11
emb_78                 11
emb_79                 11
emb_80                 11
emb_81                 11
emb_82                 11
emb_83                 11
emb_84                 11
emb_85                 11
emb_86                 11
emb_87                 11
emb_88                 11
emb_89                 11
emb_90                 11
emb_91                 11
emb_92                 11
emb_93                 11
emb_94                 11
emb_95                 11
emb_96                 11
emb_97                 11
emb_98                 11
emb_99                 11
emb_100                11
emb_101                11
emb_102                11
emb_103                11
emb_104                11
emb_105                11
emb_106                11
emb_107                11
emb_108                11
emb_109                11
emb_110                11
emb_111                11
emb_112                11
emb_113                11
emb_114                11
emb_115                11
emb_116                11
emb_117                11
emb_118                11
emb_119                11
emb_120                11
emb_121                11
emb_122                11
emb_123                11
emb_124                11
emb_125                11
emb_126                11
emb_127                11
emb_128                11
emb_129                11
emb_130                11
emb_131                11
emb_132                11
emb_133                11
emb_134                11
emb_135                11
emb_136                11
emb_137                11
emb_138                11
emb_139                11
emb_140                11
emb_141                11
emb_142                11
emb_143                11
emb_144                11
emb_145                11
emb_146                11
emb_147                11
emb_148                11
emb_149                11
emb_150                11
emb_151                11
emb_152                11
emb_153                11
emb_154                11
emb_155                11
emb_156                11
emb_157                11
emb_158                11
emb_159                11
emb_160                11
emb_161                11
emb_162                11
emb_163                11
emb_164                11
emb_165                11
emb_166                11
emb_167                11
emb_168                11
emb_169                11
emb_170                11
emb_171                11
emb_172                11
emb_173                11
emb_174                11
emb_175                11
emb_176                11
emb_177                11
emb_178                11
emb_179                11
emb_180                11
emb_181                11
emb_182                11
emb_183                11
emb_184                11
emb_185                11
emb_186                11
emb_187                11
emb_188                11
emb_189                11
emb_190                11
emb_191                11
emb_192                11
emb_193                11
emb_194                11
emb_195                11
emb_196                11
emb_197                11
emb_198                11
emb_199                11
emb_200                11
emb_201                11
emb_202                11
emb_203                11
emb_204                11
emb_205                11
emb_206                11
emb_207                11
emb_208                11
emb_209                11
emb_210                11
emb_211                11
emb_212                11
emb_213                11
emb_214                11
emb_215                11
emb_216                11
emb_217                11
emb_218                11
emb_219                11
emb_220                11
emb_221                11
emb_222                11
emb_223                11
emb_224                11
emb_225                11
emb_226                11
emb_227                11
emb_228                11
emb_229                11
emb_230                11
emb_231                11
emb_232                11
emb_233                11
emb_234                11
emb_235                11
emb_236                11
emb_237                11
emb_238                11
emb_239                11
emb_240                11
emb_241                11
emb_242                11
emb_243                11
emb_244                11
emb_245                11
emb_246                11
emb_247                11
emb_248                11
emb_249                11
emb_250                11
emb_251                11
emb_252                11
emb_253                11
emb_254                11
emb_255                11
emb_256                11
emb_257                11
emb_258                11
emb_259                11
emb_260                11
emb_261                11
emb_262                11
emb_263                11
emb_264                11
emb_265                11
emb_266                11
emb_267                11
emb_268                11
emb_269                11
emb_270                11
emb_271                11
emb_272                11
emb_273                11
emb_274                11
emb_275                11
emb_276                11
emb_277                11
emb_278                11
emb_279                11
emb_280                11
emb_281                11
emb_282                11
emb_283                11
emb_284                11
emb_285                11
emb_286                11
emb_287                11
emb_288                11
emb_289                11
emb_290                11
emb_291                11
emb_292                11
emb_293                11
emb_294                11
emb_295                11
emb_296                11
emb_297                11
emb_298                11
emb_299                11
emb_300                11
emb_301                11
emb_302                11
emb_303                11
emb_304                11
emb_305                11
emb_306                11
emb_307                11
emb_308                11
emb_309                11
emb_310                11
emb_311                11
emb_312                11
emb_313                11
emb_314                11
emb_315                11
emb_316                11
emb_317                11
emb_318                11
emb_319                11
emb_320                11
emb_321                11
emb_322                11
emb_323                11
emb_324                11
emb_325                11
emb_326                11
emb_327                11
emb_328                11
emb_329                11
emb_330                11
emb_331                11
emb_332                11
emb_333                11
emb_334                11
emb_335                11
emb_336                11
emb_337                11
emb_338                11
emb_339                11
emb_340                11
emb_341                11
emb_342                11
emb_343                11
emb_344                11
emb_345                11
emb_346                11
emb_347                11
emb_348                11
emb_349                11
emb_350                11
emb_351                11
emb_352                11
emb_353                11
emb_354                11
emb_355                11
emb_356                11
emb_357                11
emb_358                11
emb_359                11
emb_360                11
emb_361                11
emb_362                11
emb_363                11
emb_364                11
emb_365                11
emb_366                11
emb_367                11
emb_368                11
emb_369                11
emb_370                11
emb_371                11
emb_372                11
emb_373                11
emb_374                11
emb_375                11
emb_376                11
emb_377                11
emb_378                11
emb_379                11
emb_380                11
emb_381                11
emb_382                11
emb_383                11
emb_384                11
emb_385                11
emb_386                11
emb_387                11
emb_388                11
emb_389                11
emb_390                11
emb_391                11
emb_392                11
emb_393                11
emb_394                11
emb_395                11
emb_396                11
emb_397                11
emb_398                11
emb_399                11
emb_400                11
emb_401                11
emb_402                11
emb_403                11
emb_404                11
emb_405                11
emb_406                11
emb_407                11
emb_408                11
emb_409                11
emb_410                11
emb_411                11
emb_412                11
emb_413                11
emb_414                11
emb_415                11
emb_416                11
emb_417                11
emb_418                11
emb_419                11
emb_420                11
emb_421                11
emb_422                11
emb_423                11
emb_424                11
emb_425                11
emb_426                11
emb_427                11
emb_428                11
emb_429                11
emb_430                11
emb_431                11
emb_432                11
emb_433                11
emb_434                11
emb_435                11
emb_436                11
emb_437                11
emb_438                11
emb_439                11
emb_440                11
emb_441                11
emb_442                11
emb_443                11
emb_444                11
emb_445                11
emb_446                11
emb_447                11
emb_448                11
emb_449                11
emb_450                11
emb_451                11
emb_452                11
emb_453                11
emb_454                11
emb_455                11
emb_456                11
emb_457                11
emb_458                11
emb_459                11
emb_460                11
emb_461                11
emb_462                11
emb_463                11
emb_464                11
emb_465                11
emb_466                11
emb_467                11
emb_468                11
emb_469                11
emb_470                11
emb_471                11
emb_472                11
emb_473                11
emb_474                11
emb_475                11
emb_476                11
emb_477                11
emb_478                11
emb_479                11
emb_480                11
emb_481                11
emb_482                11
emb_483                11
emb_484                11
emb_485                11
emb_486                11
emb_487                11
emb_488                11
emb_489                11
emb_490                11
emb_491                11
emb_492                11
emb_493                11
emb_494                11
emb_495                11
emb_496                11
emb_497                11
emb_498                11
emb_499                11
emb_500                11
emb_501                11
emb_502                11
emb_503                11
emb_504                11
emb_505                11
emb_506                11
emb_507                11
emb_508                11
emb_509                11
emb_510                11
emb_511                11

We recommend preprocessing discrete columns that can have many values, using 'update_transformers'. Or you may drop columns that are not necessary to model. (Exit this script using ctrl-C)
[2025-10-15 00:08:09] Saving trained synthesizer to 2_poc_simulacra\GSE42861_CTGAN_synthesizer_seed_42.pkl
[2025-10-15 00:08:10] Synthesizer saved successfully
[2025-10-15 00:08:10] CTGAN synthesizer training completed in 1182.35 seconds
[2025-10-15 00:08:10] Generating 10.0x synthetic data with CTGAN (LONG OPERATION)...
[2025-10-15 00:08:52] Synthetic data generation completed in 1224.07 seconds
[2025-10-15 00:08:52] Testing CTGAN with 0.2x augmentation...
[2025-10-15 00:08:52] Testing CTGAN with 0.5x augmentation...
[2025-10-15 00:08:52] Testing CTGAN with 10.0x augmentation...
[2025-10-15 00:08:53] Total CTGAN processing time: 1224.94 seconds
[2025-10-15 00:08:53] === Training TVAE Augmented Classifiers ===
[2025-10-15 00:08:53] Creating new synthesizer for TVAE...
[2025-10-15 00:08:53] Creating metadata for TVAE...
[2025-10-15 00:08:53] Metadata saved to 2_poc_simulacra\GSE42861_TVAE_metadata_seed_42.json
[2025-10-15 00:08:53] Training TVAE synthesizer (LONG OPERATION)...
[2025-10-15 00:08:53] Using CUDA acceleration for TVAE

C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:162: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:128: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

[2025-10-15 00:32:20] Saving trained synthesizer to 2_poc_simulacra\GSE42861_TVAE_synthesizer_seed_42.pkl
[2025-10-15 00:32:21] Synthesizer saved successfully
[2025-10-15 00:32:21] TVAE synthesizer training completed in 1408.00 seconds
[2025-10-15 00:32:21] Generating 10.0x synthetic data with TVAE (LONG OPERATION)...
[2025-10-15 00:32:54] Synthetic data generation completed in 1441.33 seconds
[2025-10-15 00:32:54] Testing TVAE with 0.2x augmentation...
[2025-10-15 00:32:55] Testing TVAE with 0.5x augmentation...
[2025-10-15 00:32:55] Testing TVAE with 10.0x augmentation...
[2025-10-15 00:32:55] Total TVAE processing time: 1442.36 seconds
[2025-10-15 00:32:55] Saving benchmark results to 2_poc_simulacra\GSE42861_benchmark_seed_42_mults_0.2-0.5-10.pkl...
[2025-10-15 00:32:58] Benchmark results saved successfully
[2025-10-15 00:32:58]
=== Running benchmark with seed 931782 ===
[2025-10-15 00:32:58] Starting benchmark for GSE42861 with seed 931782 and multipliers (0.2, 0.5, 10.0)...
[2025-10-15 00:32:58] CUDA usage: Enabled
[2025-10-15 00:32:58] Loading combined embeddings with target...
[2025-10-15 00:32:58] Split sizes - Train: 551, Test: 138
[2025-10-15 00:32:58] === Training Baseline Classifier (no augmentation) ===
[2025-10-15 00:32:58] === Training GaussianCopula Augmented Classifiers ===
[2025-10-15 00:32:58] Creating new synthesizer for GaussianCopula...
[2025-10-15 00:32:58] Creating metadata for GaussianCopula...
[2025-10-15 00:32:58] Metadata saved to 2_poc_simulacra\GSE42861_GaussianCopula_metadata_seed_931782.json
[2025-10-15 00:32:58] Training GaussianCopula synthesizer (LONG OPERATION)...

C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:162: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:128: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

[2025-10-15 00:33:43] Saving trained synthesizer to 2_poc_simulacra\GSE42861_GaussianCopula_synthesizer_seed_931782.pkl
[2025-10-15 00:33:43] Synthesizer saved successfully
[2025-10-15 00:33:43] GaussianCopula synthesizer training completed in 45.21 seconds
[2025-10-15 00:33:43] Generating 10.0x synthetic data with GaussianCopula (LONG OPERATION)...
[2025-10-15 00:34:18] Synthetic data generation completed in 80.24 seconds
[2025-10-15 00:34:18] Testing GaussianCopula with 0.2x augmentation...
[2025-10-15 00:34:18] Testing GaussianCopula with 0.5x augmentation...
[2025-10-15 00:34:18] Testing GaussianCopula with 10.0x augmentation...
[2025-10-15 00:34:19] Total GaussianCopula processing time: 81.23 seconds
[2025-10-15 00:34:19] === Training CTGAN Augmented Classifiers ===
[2025-10-15 00:34:19] Creating new synthesizer for CTGAN...
[2025-10-15 00:34:19] Creating metadata for CTGAN...
[2025-10-15 00:34:19] Metadata saved to 2_poc_simulacra\GSE42861_CTGAN_metadata_seed_931782.json
[2025-10-15 00:34:19] Training CTGAN synthesizer (LONG OPERATION)...
[2025-10-15 00:34:19] Using CUDA acceleration for CTGAN

C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:162: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:128: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

PerformanceAlert: Using the CTGANSynthesizer on this data is not recommended. To model this data, CTGAN will generate a large number of columns.

Original Column Name   Est # of Columns (CTGAN)
disease                2
emb_0                  11
emb_1                  11
emb_2                  11
emb_3                  11
emb_4                  11
emb_5                  11
emb_6                  11
emb_7                  11
emb_8                  11
emb_9                  11
emb_10                 11
emb_11                 11
emb_12                 11
emb_13                 11
emb_14                 11
emb_15                 11
emb_16                 11
emb_17                 11
emb_18                 11
emb_19                 11
emb_20                 11
emb_21                 11
emb_22                 11
emb_23                 11
emb_24                 11
emb_25                 11
emb_26                 11
emb_27                 11
emb_28                 11
emb_29                 11
emb_30                 11
emb_31                 11
emb_32                 11
emb_33                 11
emb_34                 11
emb_35                 11
emb_36                 11
emb_37                 11
emb_38                 11
emb_39                 11
emb_40                 11
emb_41                 11
emb_42                 11
emb_43                 11
emb_44                 11
emb_45                 11
emb_46                 11
emb_47                 11
emb_48                 11
emb_49                 11
emb_50                 11
emb_51                 11
emb_52                 11
emb_53                 11
emb_54                 11
emb_55                 11
emb_56                 11
emb_57                 11
emb_58                 11
emb_59                 11
emb_60                 11
emb_61                 11
emb_62                 11
emb_63                 11
emb_64                 11
emb_65                 11
emb_66                 11
emb_67                 11
emb_68                 11
emb_69                 11
emb_70                 11
emb_71                 11
emb_72                 11
emb_73                 11
emb_74                 11
emb_75                 11
emb_76                 11
emb_77                 11
emb_78                 11
emb_79                 11
emb_80                 11
emb_81                 11
emb_82                 11
emb_83                 11
emb_84                 11
emb_85                 11
emb_86                 11
emb_87                 11
emb_88                 11
emb_89                 11
emb_90                 11
emb_91                 11
emb_92                 11
emb_93                 11
emb_94                 11
emb_95                 11
emb_96                 11
emb_97                 11
emb_98                 11
emb_99                 11
emb_100                11
emb_101                11
emb_102                11
emb_103                11
emb_104                11
emb_105                11
emb_106                11
emb_107                11
emb_108                11
emb_109                11
emb_110                11
emb_111                11
emb_112                11
emb_113                11
emb_114                11
emb_115                11
emb_116                11
emb_117                11
emb_118                11
emb_119                11
emb_120                11
emb_121                11
emb_122                11
emb_123                11
emb_124                11
emb_125                11
emb_126                11
emb_127                11
emb_128                11
emb_129                11
emb_130                11
emb_131                11
emb_132                11
emb_133                11
emb_134                11
emb_135                11
emb_136                11
emb_137                11
emb_138                11
emb_139                11
emb_140                11
emb_141                11
emb_142                11
emb_143                11
emb_144                11
emb_145                11
emb_146                11
emb_147                11
emb_148                11
emb_149                11
emb_150                11
emb_151                11
emb_152                11
emb_153                11
emb_154                11
emb_155                11
emb_156                11
emb_157                11
emb_158                11
emb_159                11
emb_160                11
emb_161                11
emb_162                11
emb_163                11
emb_164                11
emb_165                11
emb_166                11
emb_167                11
emb_168                11
emb_169                11
emb_170                11
emb_171                11
emb_172                11
emb_173                11
emb_174                11
emb_175                11
emb_176                11
emb_177                11
emb_178                11
emb_179                11
emb_180                11
emb_181                11
emb_182                11
emb_183                11
emb_184                11
emb_185                11
emb_186                11
emb_187                11
emb_188                11
emb_189                11
emb_190                11
emb_191                11
emb_192                11
emb_193                11
emb_194                11
emb_195                11
emb_196                11
emb_197                11
emb_198                11
emb_199                11
emb_200                11
emb_201                11
emb_202                11
emb_203                11
emb_204                11
emb_205                11
emb_206                11
emb_207                11
emb_208                11
emb_209                11
emb_210                11
emb_211                11
emb_212                11
emb_213                11
emb_214                11
emb_215                11
emb_216                11
emb_217                11
emb_218                11
emb_219                11
emb_220                11
emb_221                11
emb_222                11
emb_223                11
emb_224                11
emb_225                11
emb_226                11
emb_227                11
emb_228                11
emb_229                11
emb_230                11
emb_231                11
emb_232                11
emb_233                11
emb_234                11
emb_235                11
emb_236                11
emb_237                11
emb_238                11
emb_239                11
emb_240                11
emb_241                11
emb_242                11
emb_243                11
emb_244                11
emb_245                11
emb_246                11
emb_247                11
emb_248                11
emb_249                11
emb_250                11
emb_251                11
emb_252                11
emb_253                11
emb_254                11
emb_255                11
emb_256                11
emb_257                11
emb_258                11
emb_259                11
emb_260                11
emb_261                11
emb_262                11
emb_263                11
emb_264                11
emb_265                11
emb_266                11
emb_267                11
emb_268                11
emb_269                11
emb_270                11
emb_271                11
emb_272                11
emb_273                11
emb_274                11
emb_275                11
emb_276                11
emb_277                11
emb_278                11
emb_279                11
emb_280                11
emb_281                11
emb_282                11
emb_283                11
emb_284                11
emb_285                11
emb_286                11
emb_287                11
emb_288                11
emb_289                11
emb_290                11
emb_291                11
emb_292                11
emb_293                11
emb_294                11
emb_295                11
emb_296                11
emb_297                11
emb_298                11
emb_299                11
emb_300                11
emb_301                11
emb_302                11
emb_303                11
emb_304                11
emb_305                11
emb_306                11
emb_307                11
emb_308                11
emb_309                11
emb_310                11
emb_311                11
emb_312                11
emb_313                11
emb_314                11
emb_315                11
emb_316                11
emb_317                11
emb_318                11
emb_319                11
emb_320                11
emb_321                11
emb_322                11
emb_323                11
emb_324                11
emb_325                11
emb_326                11
emb_327                11
emb_328                11
emb_329                11
emb_330                11
emb_331                11
emb_332                11
emb_333                11
emb_334                11
emb_335                11
emb_336                11
emb_337                11
emb_338                11
emb_339                11
emb_340                11
emb_341                11
emb_342                11
emb_343                11
emb_344                11
emb_345                11
emb_346                11
emb_347                11
emb_348                11
emb_349                11
emb_350                11
emb_351                11
emb_352                11
emb_353                11
emb_354                11
emb_355                11
emb_356                11
emb_357                11
emb_358                11
emb_359                11
emb_360                11
emb_361                11
emb_362                11
emb_363                11
emb_364                11
emb_365                11
emb_366                11
emb_367                11
emb_368                11
emb_369                11
emb_370                11
emb_371                11
emb_372                11
emb_373                11
emb_374                11
emb_375                11
emb_376                11
emb_377                11
emb_378                11
emb_379                11
emb_380                11
emb_381                11
emb_382                11
emb_383                11
emb_384                11
emb_385                11
emb_386                11
emb_387                11
emb_388                11
emb_389                11
emb_390                11
emb_391                11
emb_392                11
emb_393                11
emb_394                11
emb_395                11
emb_396                11
emb_397                11
emb_398                11
emb_399                11
emb_400                11
emb_401                11
emb_402                11
emb_403                11
emb_404                11
emb_405                11
emb_406                11
emb_407                11
emb_408                11
emb_409                11
emb_410                11
emb_411                11
emb_412                11
emb_413                11
emb_414                11
emb_415                11
emb_416                11
emb_417                11
emb_418                11
emb_419                11
emb_420                11
emb_421                11
emb_422                11
emb_423                11
emb_424                11
emb_425                11
emb_426                11
emb_427                11
emb_428                11
emb_429                11
emb_430                11
emb_431                11
emb_432                11
emb_433                11
emb_434                11
emb_435                11
emb_436                11
emb_437                11
emb_438                11
emb_439                11
emb_440                11
emb_441                11
emb_442                11
emb_443                11
emb_444                11
emb_445                11
emb_446                11
emb_447                11
emb_448                11
emb_449                11
emb_450                11
emb_451                11
emb_452                11
emb_453                11
emb_454                11
emb_455                11
emb_456                11
emb_457                11
emb_458                11
emb_459                11
emb_460                11
emb_461                11
emb_462                11
emb_463                11
emb_464                11
emb_465                11
emb_466                11
emb_467                11
emb_468                11
emb_469                11
emb_470                11
emb_471                11
emb_472                11
emb_473                11
emb_474                11
emb_475                11
emb_476                11
emb_477                11
emb_478                11
emb_479                11
emb_480                11
emb_481                11
emb_482                11
emb_483                11
emb_484                11
emb_485                11
emb_486                11
emb_487                11
emb_488                11
emb_489                11
emb_490                11
emb_491                11
emb_492                11
emb_493                11
emb_494                11
emb_495                11
emb_496                11
emb_497                11
emb_498                11
emb_499                11
emb_500                11
emb_501                11
emb_502                11
emb_503                11
emb_504                11
emb_505                11
emb_506                11
emb_507                11
emb_508                11
emb_509                11
emb_510                11
emb_511                11

We recommend preprocessing discrete columns that can have many values, using 'update_transformers'. Or you may drop columns that are not necessary to model. (Exit this script using ctrl-C)
[2025-10-15 00:54:58] Saving trained synthesizer to 2_poc_simulacra\GSE42861_CTGAN_synthesizer_seed_931782.pkl
[2025-10-15 00:55:00] Synthesizer saved successfully
[2025-10-15 00:55:00] CTGAN synthesizer training completed in 1240.73 seconds
[2025-10-15 00:55:00] Generating 10.0x synthetic data with CTGAN (LONG OPERATION)...
[2025-10-15 00:55:48] Synthetic data generation completed in 1288.71 seconds
[2025-10-15 00:55:48] Testing CTGAN with 0.2x augmentation...
[2025-10-15 00:55:48] Testing CTGAN with 0.5x augmentation...
[2025-10-15 00:55:48] Testing CTGAN with 10.0x augmentation...
[2025-10-15 00:55:49] Total CTGAN processing time: 1289.46 seconds
[2025-10-15 00:55:49] === Training TVAE Augmented Classifiers ===
[2025-10-15 00:55:49] Creating new synthesizer for TVAE...
[2025-10-15 00:55:49] Creating metadata for TVAE...
[2025-10-15 00:55:49] Metadata saved to 2_poc_simulacra\GSE42861_TVAE_metadata_seed_931782.json
[2025-10-15 00:55:49] Training TVAE synthesizer (LONG OPERATION)...
[2025-10-15 00:55:49] Using CUDA acceleration for TVAE

C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:162: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:128: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

[2025-10-15 01:19:03] Saving trained synthesizer to 2_poc_simulacra\GSE42861_TVAE_synthesizer_seed_931782.pkl
[2025-10-15 01:19:04] Synthesizer saved successfully
[2025-10-15 01:19:04] TVAE synthesizer training completed in 1395.36 seconds
[2025-10-15 01:19:04] Generating 10.0x synthetic data with TVAE (LONG OPERATION)...
[2025-10-15 01:19:37] Synthetic data generation completed in 1428.86 seconds
[2025-10-15 01:19:37] Testing TVAE with 0.2x augmentation...
[2025-10-15 01:19:37] Testing TVAE with 0.5x augmentation...
[2025-10-15 01:19:38] Testing TVAE with 10.0x augmentation...
[2025-10-15 01:19:38] Total TVAE processing time: 1429.57 seconds
[2025-10-15 01:19:38] Saving benchmark results to 2_poc_simulacra\GSE42861_benchmark_seed_931782_mults_0.2-0.5-10.pkl...
[2025-10-15 01:19:41] Benchmark results saved successfully
[2025-10-15 01:19:41]
=== Running benchmark with seed 8481962 ===
[2025-10-15 01:19:41] Starting benchmark for GSE42861 with seed 8481962 and multipliers (0.2, 0.5, 10.0)...
[2025-10-15 01:19:41] CUDA usage: Enabled
[2025-10-15 01:19:41] Loading combined embeddings with target...
[2025-10-15 01:19:41] Split sizes - Train: 551, Test: 138
[2025-10-15 01:19:41] === Training Baseline Classifier (no augmentation) ===
[2025-10-15 01:19:41] === Training GaussianCopula Augmented Classifiers ===
[2025-10-15 01:19:41] Creating new synthesizer for GaussianCopula...
[2025-10-15 01:19:41] Creating metadata for GaussianCopula...
[2025-10-15 01:19:41] Metadata saved to 2_poc_simulacra\GSE42861_GaussianCopula_metadata_seed_8481962.json
[2025-10-15 01:19:41] Training GaussianCopula synthesizer (LONG OPERATION)...

C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:162: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:128: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

[2025-10-15 01:20:25] Saving trained synthesizer to 2_poc_simulacra\GSE42861_GaussianCopula_synthesizer_seed_8481962.pkl
[2025-10-15 01:20:25] Synthesizer saved successfully
[2025-10-15 01:20:25] GaussianCopula synthesizer training completed in 44.25 seconds
[2025-10-15 01:20:25] Generating 10.0x synthetic data with GaussianCopula (LONG OPERATION)...
[2025-10-15 01:21:00] Synthetic data generation completed in 79.39 seconds
[2025-10-15 01:21:00] Testing GaussianCopula with 0.2x augmentation...
[2025-10-15 01:21:00] Testing GaussianCopula with 0.5x augmentation...
[2025-10-15 01:21:00] Testing GaussianCopula with 10.0x augmentation...
[2025-10-15 01:21:01] Total GaussianCopula processing time: 80.47 seconds
[2025-10-15 01:21:01] === Training CTGAN Augmented Classifiers ===
[2025-10-15 01:21:01] Creating new synthesizer for CTGAN...
[2025-10-15 01:21:01] Creating metadata for CTGAN...
[2025-10-15 01:21:02] Metadata saved to 2_poc_simulacra\GSE42861_CTGAN_metadata_seed_8481962.json
[2025-10-15 01:21:02] Training CTGAN synthesizer (LONG OPERATION)...
[2025-10-15 01:21:02] Using CUDA acceleration for CTGAN

C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:162: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:128: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

PerformanceAlert: Using the CTGANSynthesizer on this data is not recommended. To model this data, CTGAN will generate a large number of columns.

Original Column Name   Est # of Columns (CTGAN)
disease                2
emb_0                  11
emb_1                  11
emb_2                  11
emb_3                  11
emb_4                  11
emb_5                  11
emb_6                  11
emb_7                  11
emb_8                  11
emb_9                  11
emb_10                 11
emb_11                 11
emb_12                 11
emb_13                 11
emb_14                 11
emb_15                 11
emb_16                 11
emb_17                 11
emb_18                 11
emb_19                 11
emb_20                 11
emb_21                 11
emb_22                 11
emb_23                 11
emb_24                 11
emb_25                 11
emb_26                 11
emb_27                 11
emb_28                 11
emb_29                 11
emb_30                 11
emb_31                 11
emb_32                 11
emb_33                 11
emb_34                 11
emb_35                 11
emb_36                 11
emb_37                 11
emb_38                 11
emb_39                 11
emb_40                 11
emb_41                 11
emb_42                 11
emb_43                 11
emb_44                 11
emb_45                 11
emb_46                 11
emb_47                 11
emb_48                 11
emb_49                 11
emb_50                 11
emb_51                 11
emb_52                 11
emb_53                 11
emb_54                 11
emb_55                 11
emb_56                 11
emb_57                 11
emb_58                 11
emb_59                 11
emb_60                 11
emb_61                 11
emb_62                 11
emb_63                 11
emb_64                 11
emb_65                 11
emb_66                 11
emb_67                 11
emb_68                 11
emb_69                 11
emb_70                 11
emb_71                 11
emb_72                 11
emb_73                 11
emb_74                 11
emb_75                 11
emb_76                 11
emb_77                 11
emb_78                 11
emb_79                 11
emb_80                 11
emb_81                 11
emb_82                 11
emb_83                 11
emb_84                 11
emb_85                 11
emb_86                 11
emb_87                 11
emb_88                 11
emb_89                 11
emb_90                 11
emb_91                 11
emb_92                 11
emb_93                 11
emb_94                 11
emb_95                 11
emb_96                 11
emb_97                 11
emb_98                 11
emb_99                 11
emb_100                11
emb_101                11
emb_102                11
emb_103                11
emb_104                11
emb_105                11
emb_106                11
emb_107                11
emb_108                11
emb_109                11
emb_110                11
emb_111                11
emb_112                11
emb_113                11
emb_114                11
emb_115                11
emb_116                11
emb_117                11
emb_118                11
emb_119                11
emb_120                11
emb_121                11
emb_122                11
emb_123                11
emb_124                11
emb_125                11
emb_126                11
emb_127                11
emb_128                11
emb_129                11
emb_130                11
emb_131                11
emb_132                11
emb_133                11
emb_134                11
emb_135                11
emb_136                11
emb_137                11
emb_138                11
emb_139                11
emb_140                11
emb_141                11
emb_142                11
emb_143                11
emb_144                11
emb_145                11
emb_146                11
emb_147                11
emb_148                11
emb_149                11
emb_150                11
emb_151                11
emb_152                11
emb_153                11
emb_154                11
emb_155                11
emb_156                11
emb_157                11
emb_158                11
emb_159                11
emb_160                11
emb_161                11
emb_162                11
emb_163                11
emb_164                11
emb_165                11
emb_166                11
emb_167                11
emb_168                11
emb_169                11
emb_170                11
emb_171                11
emb_172                11
emb_173                11
emb_174                11
emb_175                11
emb_176                11
emb_177                11
emb_178                11
emb_179                11
emb_180                11
emb_181                11
emb_182                11
emb_183                11
emb_184                11
emb_185                11
emb_186                11
emb_187                11
emb_188                11
emb_189                11
emb_190                11
emb_191                11
emb_192                11
emb_193                11
emb_194                11
emb_195                11
emb_196                11
emb_197                11
emb_198                11
emb_199                11
emb_200                11
emb_201                11
emb_202                11
emb_203                11
emb_204                11
emb_205                11
emb_206                11
emb_207                11
emb_208                11
emb_209                11
emb_210                11
emb_211                11
emb_212                11
emb_213                11
emb_214                11
emb_215                11
emb_216                11
emb_217                11
emb_218                11
emb_219                11
emb_220                11
emb_221                11
emb_222                11
emb_223                11
emb_224                11
emb_225                11
emb_226                11
emb_227                11
emb_228                11
emb_229                11
emb_230                11
emb_231                11
emb_232                11
emb_233                11
emb_234                11
emb_235                11
emb_236                11
emb_237                11
emb_238                11
emb_239                11
emb_240                11
emb_241                11
emb_242                11
emb_243                11
emb_244                11
emb_245                11
emb_246                11
emb_247                11
emb_248                11
emb_249                11
emb_250                11
emb_251                11
emb_252                11
emb_253                11
emb_254                11
emb_255                11
emb_256                11
emb_257                11
emb_258                11
emb_259                11
emb_260                11
emb_261                11
emb_262                11
emb_263                11
emb_264                11
emb_265                11
emb_266                11
emb_267                11
emb_268                11
emb_269                11
emb_270                11
emb_271                11
emb_272                11
emb_273                11
emb_274                11
emb_275                11
emb_276                11
emb_277                11
emb_278                11
emb_279                11
emb_280                11
emb_281                11
emb_282                11
emb_283                11
emb_284                11
emb_285                11
emb_286                11
emb_287                11
emb_288                11
emb_289                11
emb_290                11
emb_291                11
emb_292                11
emb_293                11
emb_294                11
emb_295                11
emb_296                11
emb_297                11
emb_298                11
emb_299                11
emb_300                11
emb_301                11
emb_302                11
emb_303                11
emb_304                11
emb_305                11
emb_306                11
emb_307                11
emb_308                11
emb_309                11
emb_310                11
emb_311                11
emb_312                11
emb_313                11
emb_314                11
emb_315                11
emb_316                11
emb_317                11
emb_318                11
emb_319                11
emb_320                11
emb_321                11
emb_322                11
emb_323                11
emb_324                11
emb_325                11
emb_326                11
emb_327                11
emb_328                11
emb_329                11
emb_330                11
emb_331                11
emb_332                11
emb_333                11
emb_334                11
emb_335                11
emb_336                11
emb_337                11
emb_338                11
emb_339                11
emb_340                11
emb_341                11
emb_342                11
emb_343                11
emb_344                11
emb_345                11
emb_346                11
emb_347                11
emb_348                11
emb_349                11
emb_350                11
emb_351                11
emb_352                11
emb_353                11
emb_354                11
emb_355                11
emb_356                11
emb_357                11
emb_358                11
emb_359                11
emb_360                11
emb_361                11
emb_362                11
emb_363                11
emb_364                11
emb_365                11
emb_366                11
emb_367                11
emb_368                11
emb_369                11
emb_370                11
emb_371                11
emb_372                11
emb_373                11
emb_374                11
emb_375                11
emb_376                11
emb_377                11
emb_378                11
emb_379                11
emb_380                11
emb_381                11
emb_382                11
emb_383                11
emb_384                11
emb_385                11
emb_386                11
emb_387                11
emb_388                11
emb_389                11
emb_390                11
emb_391                11
emb_392                11
emb_393                11
emb_394                11
emb_395                11
emb_396                11
emb_397                11
emb_398                11
emb_399                11
emb_400                11
emb_401                11
emb_402                11
emb_403                11
emb_404                11
emb_405                11
emb_406                11
emb_407                11
emb_408                11
emb_409                11
emb_410                11
emb_411                11
emb_412                11
emb_413                11
emb_414                11
emb_415                11
emb_416                11
emb_417                11
emb_418                11
emb_419                11
emb_420                11
emb_421                11
emb_422                11
emb_423                11
emb_424                11
emb_425                11
emb_426                11
emb_427                11
emb_428                11
emb_429                11
emb_430                11
emb_431                11
emb_432                11
emb_433                11
emb_434                11
emb_435                11
emb_436                11
emb_437                11
emb_438                11
emb_439                11
emb_440                11
emb_441                11
emb_442                11
emb_443                11
emb_444                11
emb_445                11
emb_446                11
emb_447                11
emb_448                11
emb_449                11
emb_450                11
emb_451                11
emb_452                11
emb_453                11
emb_454                11
emb_455                11
emb_456                11
emb_457                11
emb_458                11
emb_459                11
emb_460                11
emb_461                11
emb_462                11
emb_463                11
emb_464                11
emb_465                11
emb_466                11
emb_467                11
emb_468                11
emb_469                11
emb_470                11
emb_471                11
emb_472                11
emb_473                11
emb_474                11
emb_475                11
emb_476                11
emb_477                11
emb_478                11
emb_479                11
emb_480                11
emb_481                11
emb_482                11
emb_483                11
emb_484                11
emb_485                11
emb_486                11
emb_487                11
emb_488                11
emb_489                11
emb_490                11
emb_491                11
emb_492                11
emb_493                11
emb_494                11
emb_495                11
emb_496                11
emb_497                11
emb_498                11
emb_499                11
emb_500                11
emb_501                11
emb_502                11
emb_503                11
emb_504                11
emb_505                11
emb_506                11
emb_507                11
emb_508                11
emb_509                11
emb_510                11
emb_511                11

We recommend preprocessing discrete columns that can have many values, using 'update_transformers'. Or you may drop columns that are not necessary to model. (Exit this script using ctrl-C)
[2025-10-15 01:41:07] Saving trained synthesizer to 2_poc_simulacra\GSE42861_CTGAN_synthesizer_seed_8481962.pkl
[2025-10-15 01:41:08] Synthesizer saved successfully
[2025-10-15 01:41:08] CTGAN synthesizer training completed in 1206.45 seconds
[2025-10-15 01:41:08] Generating 10.0x synthetic data with CTGAN (LONG OPERATION)...
[2025-10-15 01:41:46] Synthetic data generation completed in 1244.63 seconds
[2025-10-15 01:41:46] Testing CTGAN with 0.2x augmentation...
[2025-10-15 01:41:46] Testing CTGAN with 0.5x augmentation...
[2025-10-15 01:41:46] Testing CTGAN with 10.0x augmentation...
[2025-10-15 01:41:47] Total CTGAN processing time: 1245.40 seconds
[2025-10-15 01:41:47] === Training TVAE Augmented Classifiers ===
[2025-10-15 01:41:47] Creating new synthesizer for TVAE...
[2025-10-15 01:41:47] Creating metadata for TVAE...
[2025-10-15 01:41:47] Metadata saved to 2_poc_simulacra\GSE42861_TVAE_metadata_seed_8481962.json
[2025-10-15 01:41:47] Training TVAE synthesizer (LONG OPERATION)...
[2025-10-15 01:41:47] Using CUDA acceleration for TVAE

C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:162: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
C:\Users\ferdi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sdv\single_table\base.py:128: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

[2025-10-15 02:03:13] Saving trained synthesizer to 2_poc_simulacra\GSE42861_TVAE_synthesizer_seed_8481962.pkl
[2025-10-15 02:03:14] Synthesizer saved successfully
[2025-10-15 02:03:14] TVAE synthesizer training completed in 1287.35 seconds
[2025-10-15 02:03:14] Generating 10.0x synthetic data with TVAE (LONG OPERATION)...
[2025-10-15 02:03:49] Synthetic data generation completed in 1321.95 seconds
[2025-10-15 02:03:49] Testing TVAE with 0.2x augmentation...
[2025-10-15 02:03:49] Testing TVAE with 0.5x augmentation...
[2025-10-15 02:03:49] Testing TVAE with 10.0x augmentation...
[2025-10-15 02:03:49] Total TVAE processing time: 1322.62 seconds
[2025-10-15 02:03:49] Saving benchmark results to 2_poc_simulacra\GSE42861_benchmark_seed_8481962_mults_0.2-0.5-10.pkl...
[2025-10-15 02:03:52] Benchmark results saved successfully
[2025-10-15 02:03:52]
=== Computing Statistics Across Seeds ===
[2025-10-15 02:03:52]
=== BENCHMARK RESULTS SUMMARY ===
[2025-10-15 02:03:52] Method                Accuracy (mean ± std)    F1 Macro (mean ± std)
[2025-10-15 02:03:52] ----------------------------------------------------------------------
[2025-10-15 02:03:52] baseline             0.7415 ± 0.0385        0.7412 ± 0.0383
[2025-10-15 02:03:52] CTGAN_0.2x           0.7440 ± 0.0385        0.7435 ± 0.0383
[2025-10-15 02:03:52] CTGAN_0.5x           0.7367 ± 0.0416        0.7364 ± 0.0413
[2025-10-15 02:03:52] CTGAN_10x            0.7415 ± 0.0149        0.7404 ± 0.0148
[2025-10-15 02:03:52] GaussianCopula_0.2x  0.7367 ± 0.0385        0.7364 ± 0.0384
[2025-10-15 02:03:52] GaussianCopula_0.5x  0.7295 ± 0.0452        0.7292 ± 0.0451
[2025-10-15 02:03:52] GaussianCopula_10x   0.7343 ± 0.0503        0.7337 ± 0.0501
[2025-10-15 02:03:52] TVAE_0.2x            0.7464 ± 0.0355        0.7460 ± 0.0353
[2025-10-15 02:03:52] TVAE_0.5x            0.7367 ± 0.0416        0.7364 ± 0.0413
[2025-10-15 02:03:52] TVAE_10x             0.7440 ± 0.0068        0.7433 ± 0.0070
[2025-10-15 02:03:52] Saving results to CSV file...
[2025-10-15 02:03:52] Results saved to 2_poc_simulacra\GSE42861_benchmark_results.csv
[2025-10-15 02:03:52] CSV results saved to: 2_poc_simulacra\GSE42861_benchmark_results.csv
[2025-10-15 02:03:52]
CSV Preview (first 10 rows):

,accession,dnam_path,metadata_path,target_column,seed,method,multiplier,accuracy,f1_macro,test_size,train_size,timestamp
0,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,42,baseline,NaN,0.789855,0.789313,138.0,551.0,2025-10-15 02:03:52
1,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,42,GaussianCopula_0.2x,0.2,0.782609,0.782197,138.0,661.0,2025-10-15 02:03:52
2,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,42,GaussianCopula_0.5x,0.5,0.789855,0.789579,138.0,826.0,2025-10-15 02:03:52
3,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,42,GaussianCopula_10x,10.0,0.804348,0.803512,138.0,6061.0,2025-10-15 02:03:52
4,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,42,CTGAN_0.2x,0.2,0.789855,0.789313,138.0,661.0,2025-10-15 02:03:52
5,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,42,CTGAN_0.5x,0.5,0.789855,0.789313,138.0,826.0,2025-10-15 02:03:52
6,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,42,CTGAN_10x,10.0,0.724638,0.724116,138.0,6061.0,2025-10-15 02:03:52
7,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,42,TVAE_0.2x,0.2,0.789855,0.789313,138.0,661.0,2025-10-15 02:03:52
8,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,42,TVAE_0.5x,0.5,0.789855,0.789313,138.0,826.0,2025-10-15 02:03:52
9,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,42,TVAE_10x,10.0,0.739130,0.739076,138.0,6061.0,2025-10-15 02:03:52
10,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,931782,baseline,NaN,0.695652,0.695588,138.0,551.0,2025-10-15 02:03:52
11,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,931782,GaussianCopula_0.2x,0.2,0.688406,0.688258,138.0,661.0,2025-10-15 02:03:52
12,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,931782,GaussianCopula_0.5x,0.5,0.681159,0.681092,138.0,826.0,2025-10-15 02:03:52
13,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,931782,GaussianCopula_10x,10.0,0.688406,0.687996,138.0,6061.0,2025-10-15 02:03:52
14,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,931782,CTGAN_0.2x,0.2,0.695652,0.695588,138.0,661.0,2025-10-15 02:03:52
15,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,931782,CTGAN_0.5x,0.5,0.688406,0.688389,138.0,826.0,2025-10-15 02:03:52
16,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,931782,CTGAN_10x,10.0,0.739130,0.737143,138.0,6061.0,2025-10-15 02:03:52
17,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,931782,TVAE_0.2x,0.2,0.702899,0.702883,138.0,661.0,2025-10-15 02:03:52
18,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,931782,TVAE_0.5x,0.5,0.688406,0.688389,138.0,826.0,2025-10-15 02:03:52
19,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,931782,TVAE_10x,10.0,0.739130,0.737753,138.0,6061.0,2025-10-15 02:03:52
20,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,8481962,baseline,NaN,0.739130,0.738636,138.0,551.0,2025-10-15 02:03:52
21,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,8481962,GaussianCopula_0.2x,0.2,0.739130,0.738636,138.0,661.0,2025-10-15 02:03:52
22,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,8481962,GaussianCopula_0.5x,0.5,0.717391,0.717020,138.0,826.0,2025-10-15 02:03:52
23,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,8481962,GaussianCopula_10x,10.0,0.710145,0.709596,138.0,6061.0,2025-10-15 02:03:52
24,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,8481962,CTGAN_0.2x,0.2,0.746377,0.745723,138.0,661.0,2025-10-15 02:03:52
25,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,8481962,CTGAN_0.5x,0.5,0.731884,0.731532,138.0,826.0,2025-10-15 02:03:52
26,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,8481962,CTGAN_10x,10.0,0.760870,0.759848,138.0,6061.0,2025-10-15 02:03:52
27,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,8481962,TVAE_0.2x,0.2,0.746377,0.745723,138.0,661.0,2025-10-15 02:03:52
28,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,8481962,TVAE_0.5x,0.5,0.731884,0.731532,138.0,826.0,2025-10-15 02:03:52
29,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,8481962,TVAE_10x,10.0,0.753623,0.753157,138.0,6061.0,2025-10-15 02:03:52
30,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,SUMMARY,baseline,NaN,0.741546,0.741179,NaN,NaN,2025-10-15 02:03:52
31,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,SUMMARY,CTGAN_0.2x,NaN,0.743961,0.743541,NaN,NaN,2025-10-15 02:03:52
32,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,SUMMARY,CTGAN_0.5x,NaN,0.736715,0.736411,NaN,NaN,2025-10-15 02:03:52
33,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,SUMMARY,CTGAN_10x,NaN,0.741546,0.740369,NaN,NaN,2025-10-15 02:03:52
34,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,SUMMARY,GaussianCopula_0.2x,NaN,0.736715,0.736364,NaN,NaN,2025-10-15 02:03:52
35,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,SUMMARY,GaussianCopula_0.5x,NaN,0.729469,0.729230,NaN,NaN,2025-10-15 02:03:52
36,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,SUMMARY,GaussianCopula_10x,NaN,0.734300,0.733701,NaN,NaN,2025-10-15 02:03:52
37,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,SUMMARY,TVAE_0.2x,NaN,0.746377,0.745973,NaN,NaN,2025-10-15 02:03:52
38,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,SUMMARY,TVAE_0.5x,NaN,0.736715,0.736411,NaN,NaN,2025-10-15 02:03:52
39,GSE42861,2_poc_simulacra\dnam.csv,2_poc_simulacra\metadata.csv,disease,SUMMARY,TVAE_10x,NaN,0.743961,0.743329,NaN,NaN,2025-10-15 02:03:52